### ISSUE TITLE
Possible to share symbol cache between connections?

### ISSUE THREAD

**Issue by jasonewang** [jhump/protoreflect#130]
I have multiple instances a service and I would like to only have to resolve the service descriptor once and cache the symbols for use across different connections. Are there issues with sharing the symbol cache across different connections? Are there plans to allow users to plug in a cache on a per-connection basis?

**Comment by jhump** [comment]
> Are there issues with sharing the symbol cache across different connections?

The remote servers could have different definitions of the services. This is of course possible even when using the same `*grpc.ClientConn` but spreading queries over multiple streams: under-the-hood there could be multiple connections to different servers. But since the backend servers for a single `*grpc.ClientConn` should be homogenous, it seems sufficiently low risk to cache across them.

But caching *across* connections is definitely not safe as there is no way the client can know that they are "homogenous" with respect to their definition of a given service.

If you retrieve the service from one connection and can safely assume it is the same across connections in your environment, why is your code trying to re-resolve the service with other connections? Or do the servers also expose other non-shared servers, and you just want to avoid re-resolving/re-downloading the service that is shared?

I had not imagined allowing users to plugin custom caching behavior since that feels like overkill. But perhaps I could be convinced otherwise -- I'd need more info about the case that is causing you issues though. Can you not work around this in your own code, like with your own cache layer or a `sync.Once`?

**Comment by jasonewang** [comment]
I just wanted to avoid re-resolving services. On a closer look I _can_ just cache the ServiceDescriptors myself and I don't need to directly access the underlying FileDescriptors for symbol lookup. Thanks.
