### ISSUE TITLE
 Why do not support  map

### ISSUE THREAD

**Issue by hacktmz** [jhump/protoreflect#131]
unmarshal map error，

Unmarshal body to inner.HelloResponse: unexpected EOF

**Comment by jhump** [comment]
@hacktmz, there are tests that show that maps are in [fact](https://github.com/jhump/protoreflect/blob/e919d4ddce237a9757b3c397c1b8e1071df842cc/dynamic/binary_test.go#L26) [supported](https://github.com/jhump/protoreflect/blob/e919d4ddce237a9757b3c397c1b8e1071df842cc/dynamic/binary_test.go#L36). However, if your map has an enum as its value type, that is broken right now due to upstream issue in protobuf library: https://github.com/golang/protobuf/issues/644

In any event, if you could provide more details, like the code you are using, the definition of the proto message, and perhaps even the body you are trying to unmarshal (like in text format), that would be much more helpful so we can reproduce what you are seeing.
