### ISSUE TITLE
Example to unmarshal ([] byte) input for photo

### ISSUE THREAD

**Issue by amohit1315** [jhump/protoreflect#142]
hi,
I am trying to use 
https://godoc.org/github.com/jhump/protoreflect/desc
https://godoc.org/github.com/jhump/protoreflect/dynamic

to unmarshal buffer([] byte) input to my photo file.

---------------------------------------------
desc2,_ := desc.LoadMessageDescriptorForMessage(telemetry_top.TelemetryStream)
dy := dynamic.NewMessage(desc2)
fmt.Println(dy.Unmarshal(buf))
-----------------------------------------------

but when I run this I get -

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x61b869]

goroutine 1 [running]:
github.com/jhump/protoreflect/desc.(*MessageDescriptor).FindFieldByNumber(...)
	/b/amohit/go/src/github.com/jhump/protoreflect/desc/descriptor.go:673
github.com/jhump/protoreflect/dynamic.(*Message).FindFieldDescriptor(0xc420055e98, 0x200000001, 0x0)
	/b/amohit/go/src/github.com/jhump/protoreflect/dynamic/dynamic_message.go:244 +0x29
github.com/jhump/protoreflect/dynamic.(*Message).unmarshal(0xc420055e98, 0xc420055de0, 0x410100, 0x6cbc60, 0x0)
	/b/amohit/go/src/github.com/jhump/protoreflect/dynamic/binary.go:407 +0x7b
github.com/jhump/protoreflect/dynamic.(*Message).UnmarshalMerge(0xc420055e98, 0xc4200be000, 0x499, 0xffff, 0xc42007d350, 0xffff)
	/b/amohit/go/src/github.com/jhump/protoreflect/dynamic/binary.go:390 +0x89
github.com/jhump/protoreflect/dynamic.(*Message).Unmarshal(0xc420055e98, 0xc4200be000, 0x499, 0xffff, 0x0, 0x499)
	/b/amohit/go/src/github.com/jhump/protoreflect/dynamic/binary.go:379 +0x75
main.Parse(0xc4200be000, 0x499, 0xffff)
	/b/amohit/go/src/github.com/influxdata/telegraf/plugins/parsers/juniperUDP/server.go:68 +0xad
main.main()
	/b/amohit/go/src/github.com/influxdata/telegraf/plugins/parsers/juniperUDP/server.go:54 +0x19d
exit status 2

Can you please provide an example on how to Unmarshal buffer([] bytes) input for photo.

**Comment by jhump** [comment]
That stack trace suggests that the message descriptor might be nil. Instead of ignoring the returned error, try examining it -- there may have been an error in extracting the descriptor for the given type.

If that is not the problem and the error is `nil`, could you provide a full example repro case so that we can debug and fix? (E.g. provide proto source for a message that reproduces the problem as well as the actual data bytes you are trying to unmarshal when the panic is triggered.)

**Comment by jhump** [comment]
@amohit1315, are you still having this problem? If there is a bug in this library, I would love to fix it. But I cannot reproduce. If I don't hear back from you, I'm going to close this issue.

**Comment by amohit1315** [comment]
[proto_server.zip](https://github.com/jhump/protoreflect/files/2255869/proto_server.zip)

Uploaded proto files and the go code.
We get the data over Udp stream in these proto format.
Looking for a way to unmarshal and also process the extensions that is being used in another proto file.

Will be helpful if you can provide a small example to do the above two things, and also look at the above go code and point out error.
Thanks.

**Comment by amohit1315** [comment]
If u need any more information let me know

**Comment by jhump** [comment]
@amohit1315, did you read my earlier comment? Instead of ignoring the error that can be returned from `desc.LoadMessageDescriptorForMessage`, you should inspect it. Perhaps there is an issue in loading and linking the descriptor.

I admit that I can't tell what kind of error that might reveal from the attached source. But if your real source code has import statements that were not in the attachment, those can often be an issue with linking the descriptor: your import statements need to refer to the file (with relative path) in exactly the same way as your invocation to `protoc` when generating Go code from the files. See https://github.com/golang/protobuf/issues/567 for more details.

I cannot reproduce the error you are seeing from the attached files. Also, it isn't clear why you are using dynamic messages at all here. Since you know the type, just use `proto.Unmarshal` directly into the generated struct.

**Comment by amohit1315** [comment]
@jhump I am attaching the new set of files with simplified sample proto that you can use to reproduce the error. For reproducing the scenarios locally, I have modified the script to use some static data. But in real use case, we would receive messages on a UDP port(which are sent by different devices to the server)
[Parser.zip](https://github.com/jhump/protoreflect/files/2261757/Parser.zip)


We have multiple(~20) proto files having multiple levels of extensions defined in different proto files. 
I want to parse the incoming data generically without hardcoding what fields needs to be decoded.
Making the code independent , i.e If there is some changes in the proto files(addition/deletion of fields) then the code doesn't need to be modified to reflect the proto changes but only update latest proto files.

We tried using proto.Unmarshal [https://godoc.org/github.com/golang/protobuf/proto](url). With this we were able to parse single level of extension after using proto.unmarshal() [
https://godoc.org/github.com/golang/protobuf/proto#GetExtension](url) but the return type of this is (interface{}, error). We cannot apply getExtension again on this interface{} returned type. So we were trying to use [https://godoc.org/github.com/jhump/protoreflect](url) unmarshal as well as handle multiple level of extensions as the dynamic library provides features for generalization.

In the above attached code, we are trying to create an empty dynamic message object of type 
system (message.proto) and then use dynamic unmarshal() method to unmarshal the buffer object, so that we can parse extensions after unmarshal. But the output returned is nil.

I also added a check at LoadMessageDescriptorForMessage() to see if something went wrong at that point but there was no error at this point.

Can you point out what we are doing wrong as well as can we use dynamic library to parse multiple level of extensions?

**Comment by jhump** [comment]
@amohit1315, I'm afraid your new ZIP file does not demonstrate the problem -- everything works fine. In your original post, it was causing a nil-dereference panic.

In this code sample, it prints `<nil>`. But that is because you are printing the *error* from unmarshaling, and there is none. If you change the last line of `server.go` from this:

```go
fmt.Println(dy.Unmarshal(buf))
```

to this:

```go
	if err := dy.Unmarshal(buf); err != nil {
		panic(err)
	}
	fmt.Println(dy)
```

then it instead prints what you expect:

```
system_id:"A1" component_id:1 enterprise:<5:"my name">
```

So your "shrunk" repro case works fine. The panic you were experiencing must be due to some other difference between your "subset of code" in the repro case and your full code. As I mentioned in my last message in this thread, it sounds like it is probably related to how the files compiled using `protoc` (re-read my last message and follow the link to the protobuf issue for more details).

BTW, I still don't see any compelling reason to use a dynamic message. If your descriptors always come from `desc.LoadMessageDescriptor`, then you are only loading the latest compiled and linked version of the proto.

> Making the code independent , i.e If there is some changes in the proto files(addition/deletion of fields) then the code doesn't need to be modified to reflect the proto changes but only update latest proto files.

I don't follow this. If you "only update latest proto files", that's not dynamic usage: you are still compiling and linking in the latest version.

> We cannot apply getExtension again on this interface{} returned type

If the extension type is a message that may have its own extensions, then certainly you *can* use `proto.GetExtension` with the return type. But you must first use a type assertion to extract the actual `proto.Message` value:

```go
val := proto.GetExtension(extDesc, msg)
extMsg := val.(proto.Message)
otherVal := proto.GetExtension(otherExtDesc, extMsg)
```

All of the methods for extracting values from a dynamic message *also* return `interface{}`, so I don't see how use of a dynamic message is helpful here.

**Comment by amohit1315** [comment]
@jhump Thank you for the pointer.
In the below code:

`
fmt.Println(dy.Unmarshal(buf))
`

It was correct as it was returning <nil> as there was no error from unmarshalling.

+ Now I am able to traverse extensions using type assertion to convert to **proto.Message**.

I will explore it further to extract information.
Will be closing the issue till then.

Thanks again.
