### ISSUE TITLE
Recommended method for playing with a dynamic message in goja script?

### ISSUE THREAD

**Issue by deinspanjer** [jhump/protoreflect#171]
I have an app working that is reading .proto files and is able to create new messages by parsing bytes using a factory.

This gives me a dynamic message that I can use for things such as `person.GetFieldByName("id")`, but when in a JavaScript context such as with [goja](https://godoc.org/github.com/dop251/goja), I'd like to be able to just do `person.id`.
So far, the only way I've found is to MarshalJSON the object in the Go code, cast it to a string and store it as an object in the script's context, then call JSON.parse() inside the script.  Just wondering if anyone has recommendations for a better method.

**Comment by jhump** [comment]
I can't think of a better way. If you were trying to use the proto from JavaScript *outside* of the Go process (e.g. in a browser, instead of using Goja), I'd instead recommend using the JS protobuf library and marshaling to bytes instead of to JSON.

But for what you're talking about, you'll need to marshal to JSON. Looking at the Goja docs, I don't see a way for custom types to provide custom conversion to JS values. I suppose you might try implementing the `goja.Value` interface with a type that refers to a dynamic message and, under the hood, can translate that into a `*goja.Object` -- but that sounds pretty complicated, and it's not obvious it would even work. It looks like the way it handles mapping struct values to JS objects is internal, and not exposed for any sort of customization/extensibility.

**Comment by deinspanjer** [comment]
Okay, that is actually reassuring because it means I wasn't off in the weeds missing something. :)
This project should be open sourced soon, so I'll be sure to toss a link to you so you can see the evil things I'm doing with your lib. ;)
