### ISSUE TITLE
Parse Proto from string syntax

### ISSUE THREAD

**Issue by wilsonf** [jhump/protoreflect#184]
Hi,
I need to parse a string of simple protobuf syntax. 

Currently what I do is create a file, parse the file and delete the file. Are there any functionality in reflect that I can use?

Thanks

**Comment by jhump** [comment]
@wilsonf, yes, the [protoparse](https://godoc.org/github.com/jhump/protoreflect/desc/protoparse) package has what you need.

When you create a `Parser`, you can use a custom `Accessor` so that it loads the file contents from, for example, a constant string or a map of filename->string contents.

Here's an example that can be used with a single file that has no imports:

```go
// parse will parse the given proto source, assuming it is in a file named 'test.proto'. It
// panics if there is an error parsing the given source.
func parse(contents string) *desc.FileDescriptor {
	p := protoparse.Parser{
		Accessor: func(filename string) (io.ReadCloser, error) {
			if filename == "test.proto" {
				return ioutil.NopCloser(strings.NewReader(contents)), nil
			} else {
				return nil, os.ErrNotExist
			}
		},
	}
	fds, err := p.ParseFiles("test.proto")
	if err != nil {
		panic(err)
	}
	return fds[0]
}
```

**Comment by wilsonf** [comment]
It works! Thank you very much for your help
