### ISSUE TITLE
protoparse : Add link method to Parser

### ISSUE THREAD

**Issue by sonatard** [jhump/protoreflect#186]
I wrote command line tool using protoreflect parser. 
protoreflect is a good library!! thanks!!

Next I will write a  same functionality protoc plugin. 
protoc plugin have `descriptor.FileDescriptorProto` in CodeGeneratorRequest, but it dose not link...

 I want to use following method because Link make to write code very easy and use same code command line tool and protoc plugin. 

```go
func (p Parser) Link([]*dpb.FileDescriptorProto) ([]*desc.FileDescriptor, error)  {

}
```

**Comment by jhump** [comment]
I don't understand. The `protoc` compiler should definitely provide you descriptors that will link -- it provides the entire transitive closure of descriptors for all files being compiled.

If you want to write a protoc plugin in Go, I recommend taking a look at another library I wrote specifically for this: https://github.com/jhump/goprotoc

The `README` says it's still under construction because there are some other things in repo that aren't complete (in particular, the pure-Go re-implementation of `protoc`). The `plugins` package therein is what you're looking for, at the doc shows examples of how to write a plugin: https://github.com/jhump/goprotoc/blob/master/plugins/doc.go.

Anyhow, if you didn't want to add this other repo as a dep, then you can just look at how it converts the proto descriptors supplied by `protoc` and turns them into "rich" descriptors. That code is here: https://github.com/jhump/goprotoc/blob/master/plugins/exec.go#L159

Also, if I were to add an exported function to this repo for that functionality, it wouldn't go in `protoparse` since that is for parsing proto sources. With a plugin, `protoc` has already parsed the sources, so linking supplied proto descriptors would be something that goes in the `desc` package. But I think that package already has sufficient API for this that can be composed into what you're trying to do (as evidenced by the link above for code in the `goprotoc` repo, which uses those APIs to do what you're talking about).

I hope that helps.

**Comment by jhump** [comment]
@sonatard, if you are still running into problems, feel free to re-open this ticket. But please first take a look at my reply above to see if it helps you resolve what you're seeing. If it doesn't, please provide more details/code examples if you re-open.
