### ISSUE TITLE
Global cache variable in desc are unavoidable

### ISSUE THREAD

**Issue by pedgeio** [jhump/protoreflect#204]
There is no way to avoid hitting the global cache variables in `desc/load.go` and `desc/imports.go`:

```go
var (
	cacheMu       sync.RWMutex
	filesCache    = map[string]*FileDescriptor{}
	messagesCache = map[string]*MessageDescriptor{}
	enumCache     = map[reflect.Type]*EnumDescriptor{}
)
```

Regardless of whether you use an `ImportResolver` or not, these global variables in `desc/load.go` will be checked against and populated. This makes the `desc` unusable in e.g. a long-running service that compiles different and disparate Protocol Buffer sets - not only will this cache explode in size, but this could easily leak information across calls to `desc` methods, resulting in incorrect information being returned. If multiple independent users are relying on this, this is a security concern - two separate users could have a file of the same name with confidential contents, which will then be leaked across. 

There needs to be either/or:

- An option to disable all caching.
- An option to have a `type Cache struct` that you can use for all operations, so you can create a new one each time if you want.
- Remove these globals entirely for now. Removing these caches would not be breaking change as they are an implementation detail, and you could add in the ability to have a user cache instead.

These also exist in `desc/imports.go`:

```go
var (
	globalImportPathConf map[string]string
	globalImportPathMu   sync.RWMutex
)
```

In theory, it's possible to avoid these ever being populated (although it requires knowledge of implementation details, which is not great and prone to error), but there is no way to signify to an `ImportResolver` to not call the global `ResolveImport`.

There needs to be either/or:

- A method `TurnOffGlobalImports()` that errors/panics if `RegisterImportPath` is called, and returns nothing from `ResolveImport`
- An option `NoGlobals` on `ImportResolver`.

Preferably the former.

**Comment by jhump** [comment]
I think this bug needs to be re-phrased as functionality that does not work correctly. As far as I can tell, the only usage of the globals is (as you identified) `load.go` and `imports.go`, but those are for the `Load*` methods, which are specifically for loading metadata from the global registries in the `proto` package and _wrapping_ it with "rich descriptors". Since the registries in `proto` should be immutable after package init, the results are safe to cache.

You can, however, create file descriptors without ever interacting with these globals: use the `Create*` methods. These methods will consult the global map of import resolutions, but that is not a cache. Unless you call `desc.RegisterImport*` (or link in a package that does so), it will be empty and do nothing.

**Comment by pedgeio** [comment]
Talked offline, #206 does what I need. Thank you so much!
