### ISSUE TITLE
builder: copy field and method extensions

### ISSUE THREAD

**Issue by aberasarte** [jhump/protoreflect#227]
I was testing this amazing project and I realized that the ``builder.FromFile`` method is not copying the extensions applied to message fields and service methods. 

I'm intending to manipulate some `proto` files in order to apply changes to the fields that have a specific extension but keeping any other extension that the fields/methods could have. ¿Is something like this possible?

**Comment by jhump** [comment]
@aberasarte, I'll look into it. Preserving custom options was definitely the intention of this package, so this is probably just a bug (hopefully simple).

**Comment by jhump** [comment]
@aberasarte, how are you trying to access these custom options?

Are you examining the `Options` fields of the various builders? Or are you calling `Build` and then failing to find the expected options in the resulting descriptors?

Are the custom options you are examining linked into your program? In other words, have you run `protoc` on the file that defines your custom options and imported it into your program? If not, could you try that? You can then reference the generated `E_*` extensions to query for values from the options messages.

If the custom options are _not_ linked into your program, and you are trying to find them by tag number in the _resulting_ options messages (after calling `Build`), then I think I may see what you're missing: for that case you need to use `BuildOptions` to build the message, instead of directly calling the builder's `Build` method. And the `BuildOptions` value you use needs its `Extensions` field set so that it can interpret the custom options in question. Before populating an extension registry, you could also just try building the descriptors, but use a `BuildOptions` value that has `RequireInterpretedOptions` set to true, and see if you get an error when you try to build.

Sorry if that doesn't make much sense. If you could provide a small code sample that demonstrates the problem, I could probably help more and be more clear in my diagnosis and guidance.

Aside: I think there is actually a bug in here: you should not _have_ to create an extension registry if the custom options in question already exist in the builder's set of transitive dependencies (e.g. present in the file builder or some file that it imports).

**Comment by aberasarte** [comment]
Thanks @jhump for your quick reply! For my first test, I'm just parsing a proto file using the `protoparse`, then I use the `builder` to generate a copy and print that copy using the `protoprint`. Something like this:

```
       parser := &protoparse.Parser{
		ImportPaths:           []string{"/Users/aritz/go/src/my.package/my-api/"},
		IncludeSourceCodeInfo: true,
	}

	fd, _ := parser.ParseFiles("test/test.proto")

        builder, _ := builder.FromFile(fd[0])
	printer := &protoprint.Printer{}

	bd, _ := builder.Build()
	proto, _ := fmt.Println(printer.PrintProtoToString(bd))
	
	fmt.Println(proto)
```

If I print directly the original parsed `FileDescriptor` via `fmt.Println(printer.PrintProtoToString(bd))`, the extensions are printed. 

What I want to do is to parse that `proto` file, remove all the fields and methods that are using a certain annotation and generate a new `proto` file with the changes applied. Maybe my approach to doing this is not right.

**Comment by jhump** [comment]
@aberasarte, what you are doing makes sense. This is the case I was saying is really a bug: in your case, the custom options will be in the parsed files' transitive set of dependencies, so you should not have to use a custom extension registry.

I'm working on something that I think will help.

**Comment by jhump** [comment]
@aberasarte, do you think you could patch in #228 and see if that fixes things for you? I think it should. But I haven't finished writing tests that confirm it. If you could run it through your own case, it would be great to get info on whether it's doing for you what I think it should.

**Comment by aberasarte** [comment]
Thanks @jhump, it's working for my little test! 

I've noticed that the import statements are being printed at the bottom of the file though.

**Comment by jhump** [comment]
> I've noticed that the import statements are being printed at the bottom of the file though.

All of them? Or just some of them?

**Comment by jhump** [comment]
@aberasarte, I found why they were getting sorted incorrectly to the bottom. I pushed another commit up to that pull request. Mind pulling it down and trying again?

**Comment by aberasarte** [comment]
> All of them? Or just some of them?

I only had one import in the `proto` file.

> Mind pulling it down and trying again?

Sure! I can confirm that the change is working for my example. Thanks @jhump ! 👏 👏
