### ISSUE TITLE
getFullyQualifiedName() not using `go_package`

### ISSUE THREAD

**Issue by hitzhangjie** [jhump/protoreflect#264]
let's take following a.proto as example:

```protocol
package greeter;

option go_package = "greeter4";

message A {}
```

`protoc-gen-go` generate a.pb.go with package `greeter4`, fully qualified type of message A should be `greeter4.A`.

For now, protoreflect returns fully qualified name as `greeter.A`, rather than `greeter4.A`.

**Comment by hitzhangjie** [comment]
The reason I thinks comes here:

```go
func createMessageDescriptor(fd *FileDescriptor, parent Descriptor, enclosing string, md *dpb.DescriptorProto, symbols map[string]Descriptor) (*MessageDescriptor, string) {
	msgName := merge(enclosing, md.GetName())
	...
}

func createFileDescriptor(fd *dpb.FileDescriptorProto, deps []*FileDescriptor, r *ImportResolver) (*FileDescriptor, error) {
	ret := &FileDescriptor{
		proto:      fd,
		symbols:    map[string]Descriptor{},
		fieldIndex: map[string]map[int32]*FieldDescriptor{},
	}
	pkg := fd.GetPackage()
        ...
}
```

`encosing` is the package name returned by `fd.GetPackage()` in `createFileDescriptor(...)`, where only `package greeter` is considered, `option go_package` is not considered. We can use `fd.GetGoPackage()` to get this file option.

**Comment by hitzhangjie** [comment]
Ah, only golang consider `option go_package`, maybe we cannot do as I mentioned above.

If we use GoPackage() instead, using protoreflect in other languages will have bugs.

**Comment by jhump** [comment]
@hitzhangjie, just to explain this a little further: protoreflect provides reflection over the _protocol buffer_ language model, not Go. So it is quite intentional that the fully-qualified names it returns are the protobuf qualified names.

If you want to compute the Go name for a type, you can use API in a different repo:
https://godoc.org/github.com/jhump/goprotoc/plugins#GoNames.GoTypeForMessage
That method takes a protoreflect `*desc.MessageDescriptor` and returns information about the Go type that would be generated for it, by inspecting the Go package option of the file that contains the message.

**Comment by hitzhangjie** [comment]
Thank you, I found another solution, specifying params `M${pbfile1}=${expectedPkg}` can solve this.

Causing I am developing a general tool to generate code for multiple languages, I think this way is a little more flexible 😃 

```bash
protoc --go_out=M${pbfile1}=${expectedPackage}:. my.proto
```
