### ISSUE TITLE
Feature request: Parser.ParseString

### ISSUE THREAD

**Issue by lukesneeringer** [jhump/protoreflect#277]
Thanks for this great library, which I have been using to build an [API linter](https://github.com/googleapis/api-linter).

One feature request: The [Parser](https://godoc.org/github.com/jhump/protoreflect/desc/protoparse#Parser) type parses files, and [builders](https://godoc.org/github.com/jhump/protoreflect/desc/builder) let you construct descriptors on the fly.

For a lot of my unit tests, I find myself constructing relatively simple protos with builders. It would be great if Parser had a `ParseString` function that could take a string representing a proto file and parse it, rather than a filename.

I can understand if this was considered and rejected. Indeed, I can think of some reasons not to do it (I can imagine it would be unsuitable for use in almost every case other than tests, for example). It would make my test code a lot cleaner if it was possible, though.

**Comment by jhump** [comment]
The problem with such an API is that it is _only_ useful from tests -- because it can't handle many categories of real proto files since it would be unable to handle imports. Also, errors would have to report some hard-coded/dummy filename (which would also be included in the returned file descriptor).

I feel like having that in the package API could be confusing: users might erroneously believe they could use that instead of one of the other signatures to simplify their code, only to discover it's really useless outside of tests.

What you're asking for is a fairly simple thing to write and add to your own test package:

```go
func parseString(src string) (*desc.FileDescriptor, error) {
    var p protoparse.Parser
    p.FileAccessor = protoparse.FileContentsFromMap(map[string]string{
        "test.proto": src,
    })
    fds, err := p.ParseFiles("test.proto")
    if err != nil {
        return nil, err
    }
    return fds[0], nil
}
```

**Comment by lukesneeringer** [comment]
Thanks. I agree with you that I can not think of any other use case, and I also agree that having this in a test utility package is an equally good solution.

Much obliged.
