### ISSUE TITLE
question: how to remove all the extensions applied to messages/fields/enums...

### ISSUE THREAD

**Issue by aberasarte** [jhump/protoreflect#289]
Probably this is a silly question so feel free to close the issue if this isn't the right place to ask it.

I'm trying to parse a `proto` file and generate a new one after removing all the extensions applied to services, fields, enums, etc. I can get rid of the registered extensions using `proto.ClearAllExtensions` but I haven't found an easy way for deleting the unregistered ones.

**Comment by jhump** [comment]
> I can get rid of the registered extensions using `proto.ClearAllExtensions` but I haven't found an easy way for deleting the unregistered ones.

That should clear both kinds. It should do what the name says and remove _all_ of them.

Unless what you have is a `*dynamic.Message`, instead of a generated message (such as `descriptor.MessageOptions`or `descriptor.FileOptions`). In that case, `proto.ClearAllExtensions` won't do anything because the `proto` package doesn't understand `*dynamic.Message` and just assumes it has no extensions. So, if you are using a dynamic message, you would need to do something more elaborate:

```go
var dm *dynamic.Message
// ... set dm to descriptor options ...

// Remove all known extensions
for _, fd := range dm.GetKnownExtensions() {
    dm.ClearField(fd)
}
// And remove all unknown extensions
md := dm.GetMessageDescriptor()
for _, tag := range dm.GetUnknownFields() {
    if md.IsExtension(tag) {
        dm.ClearFieldByNumber(int(tag))
    }
}
```

**Comment by aberasarte** [comment]
Thank you very much @jhump for your help!

> That should clear both kinds. It should do what the name says and remove all of them.

You are right! I had a unit test for testing this but I did it wrong 🤦‍♂ . I think that I can't apply this for my use case though. I have a function that parses a `proto` file and  generates a `Builder` to manipulate it. For doing so, I traverse all the elements and one of the things I do is to delete all the extensions applied to messages, services, fields and so on. 

What I ended up doing is something like this:

```
        switch t := b.(type) {
	case *builder.MessageBuilder:
		t.SetOptions(&descriptor.MessageOptions{})
	case *builder.FieldBuilder:
		t.SetOptions(&descriptor.FieldOptions{})
	case *builder.EnumBuilder:
		t.SetOptions(&descriptor.EnumOptions{})
	case *builder.EnumValueBuilder:
		t.SetOptions(&descriptor.EnumValueOptions{})
	case *builder.OneOfBuilder:
		t.SetOptions(&descriptor.OneofOptions{})
	case *builder.MethodBuilder:
		t.SetOptions(&descriptor.MethodOptions{})
	case *builder.ServiceBuilder:
		t.SetOptions(&descriptor.ServiceOptions{})
        }
```

I wanted to avoid that switch case as my code is full of them but I don't know if there is any better way to do this.

**Comment by jhump** [comment]
There is, in fact, a much simpler way of dealing with this. You could actually mutate the options directly on the descriptor protos on the parsed descriptors. Since options don't impact the _structure_ of the descriptors, you don't need to convert to builders and then re-build in order to change them.

Instead, you could simply do this:

```go
func clearOptions(d desc.Descriptor) {
    d.GetOptions().Reset()
}
```

**Comment by aberasarte** [comment]
Nice! 

I think that I can't do it that way because removing options isn't the only thing I'm trying to do. If a certain option is applied to a field, method, message or whatever, I have to remove the element from its parent as well. Summarizing, there are two things I have to do for each element:

- Check if it includes the aforementioned option an if it does, remove the element from its parent.
- Clear all the options applied to it.

That's the reason why I'm creating a builder.
