### ISSUE TITLE
Feature: clear caches

### ISSUE THREAD

**Issue by letian0805** [jhump/protoreflect#290]
How to clear all FileDescriptor caches of  client after i update my grpc server?

**Comment by jhump** [comment]
@letian0805, can you be more specific? What caches? What kind of update? Are you talking things cached in the client, or something in the server? Maybe you're talking about cached descriptors in the client when using `grpcreflect`?

**Comment by letian0805** [comment]
> @letian0805, can you be more specific? What caches? What kind of update? Are you talking things cached in the client, or something in the server? Maybe you're talking about cached descriptors in the client when using `grpcreflect`?

Yes, i'm talking about cached descriptors in the client when using `grpcreflect`.
Cached descriptors should be updated after server update protobuf.

**Comment by jhump** [comment]
I think that is a bit of rat's nest.

1) _Real_ clients don't react that way to a server restart, since they get a single version of the protos compiled in that last the life of the client. So the current behavior adequately simulates the descriptors available as if they were compiled into the client.
2) Knowing when the server is updated is non-trivial. There's no out-of-the-box way for the client to tell. The best signal it has is that the stream breaks and must be re-created, but that can also happen on many kinds of transient errors. So always flushing the cache when the stream breaks is definitely not appropriate. If there are clients using streams over WAN, it is expected that the stream could break due to transient network partitioning. It is even possible for a stream to break just due to latency in the server, if keep-alives are configured (such as overloaded server or big GC pause).

Instead of trying to detect a server upgrade, I think the best this package could offer is a `Flush` method that the client could call. And that doesn't feel very useful since the client can already just re-create the `grpcreflect.Client` (which will have empty caches, and cached descriptors in the old client will get GC'ed). Can you tell me why that is not sufficient?

**Comment by letian0805** [comment]
Does it will close `grpc.ClientConn` if just drop `grpcreflect.Client` and let it reset by GC? I am worried that it can't automatically close `grpc.ClientConn`.

**Comment by jhump** [comment]
It does not and cannot close the `grpc.ClientConn`. When creating the client, you give it a stub, not a `ClientConn`.

I don't see why this is an issue. If you are worried about a connection leak, create the `ClientConn` and the reflection stub _once_ and then arrange to provide that same stub every time you re-create the `grpcreflect.Client`.

**Comment by letian0805** [comment]
Thanks a lot! I solved my problem through the method you provided.
