### ISSUE TITLE
protoparse: cannot convert *dynamic.Message to *annotations.ResourceDescriptor

### ISSUE THREAD

**Issue by michaelhly** [jhump/protoreflect#329]
I have some .proto files that look like the following
```
// internal/resource.proto
syntax = "proto3";

import "google/protobuf/descriptor.proto";

package internal;

message Resource {
  string primitive = 1;
  string another_primitive = 2;
  repeated string repeated_primitives = 3;
}

extend google.protobuf.MessageOptions {
  Resource my_resource = 1053;
}
```
```
// foo.proto
syntax = "proto3";

import "internal"

message Foo {
  option (internal.resource) = {
     repeated_primitives: [1, 2, 3]
  };
}
```

When trying to parse `foo.proto`, it gets stuck here
https://github.com/jhump/protoreflect/blob/e52bab97a7adafa869f1b0ba0385b9996587807e/dynamic/dynamic_message.go#L2246

returning error `cannot convert *dynamic.Message to
*annotations.ResourceDescriptor`.

**Comment by jhump** [comment]
I think your example is incomplete. I just tried it, and it works fine.

Your example makes no mention of `annotations.ResourceDescriptor`. Is it possible you are using a package compiled with Gogo instead of the normal protoc-gen-go plugin? If `annotations.ResourceDescriptor` does not implement the interface `github.com/golang/protobuf/proto.Message`, it would fail with that message. But that should only be possible if it were not generated by protoc-gen-go.

I suppose it's also possible what you are seeing is an older bug? Have you verified you are using the latest version of protoparse?

**Comment by michaelhly** [comment]
I ended up just generating protosets.
