### ISSUE TITLE
Dynamic unmarshal map field error.

### ISSUE THREAD

**Issue by fooevr** [jhump/protoreflect#341]
Hi, I were used dynamic package v1.7.0 to unmarshal a simple proto message which include a map field. print correct in run mode. but in debug mod catch a exception in `dynamic/dynamic_message.go` line 219. m is nil.
proto:
```proto
syntax = "proto3";
message Foo{
    map<string, int64> bar = 1;
}
```
```go
package main

import (
	"fmt"
	"github.com/jhump/protoreflect/dynamic"
	p "p/common/proto"
)

func main()  {
	f := &p.Foo{Bar: map[string]int64{}}
	f.Bar["a"] = 1
	dynamicFoo, _ := dynamic.AsDynamicMessage(f)
	bts, _ := dynamicFoo.Marshal()

	newFoo := dynamic.NewMessage(dynamicFoo.GetMessageDescriptor())
	err := newFoo.Unmarshal(bts)
	fmt.Println(newFoo.Marshal())
	fmt.Println(err)
}
```

**Comment by jhump** [comment]
When you say exception, do you mean a panic? Or do you mean the last line of this program prints an error?

If it's a panic, can you include the entire the entire stack trace? Otherwise, can you show the actual error output of the program?

Also, in your example program, can you change the code to actually inspect the errors returned from `dynamic.AsDynamicMessage` and `dynamic.Marshal`, instead of ignoring them, and run it again -- just to make sure there's no error in an earlier step?

**Comment by fooevr** [comment]
@jhump Thank you for your quick reply. Yes it's a panic, My English is not good so I can't express my thoughts accurately. 
My example was run correct before `err := newFoo.Unmarshal(bts)` and `bts` got correct value in debug mode.
In run mode all steps was run correct . It can print `fmt.Println(newFoo.Marshal())` result and err was nil.
I'll up load My example pack, could you help me to fix it? My project was affected.

The stack is:
```
github.com/jhump/protoreflect/dynamic.(*Message).Descriptor at dynamic_message.go:219
google.golang.org/protobuf/internal/impl.legacyLoadMessageDesc.func1 at legacy_message.go:108
google.golang.org/protobuf/internal/impl.legacyLoadMessageDesc at legacy_message.go:109
google.golang.org/protobuf/internal/impl.legacyLoadMessageInfo at legacy_message.go:48
google.golang.org/protobuf/internal/impl.legacyWrapMessage at legacy_message.go:31
google.golang.org/protobuf/internal/impl.Export.ProtoMessageV2Of at api_export.go:127
github.com/golang/protobuf/proto.MessageV2 at proto.go:61
github.com/golang/protobuf/proto.UnmarshalMerge at wire.go:63
github.com/golang/protobuf/proto.Unmarshal at wire.go:58
github.com/jhump/protoreflect/codec.DecodeLengthDelimitedField at decode_fields.go:196
github.com/jhump/protoreflect/codec.(*Buffer).decodeKnownField at decode_fields.go:270
github.com/jhump/protoreflect/codec.(*Buffer).DecodeFieldValue at decode_fields.go:109
github.com/jhump/protoreflect/dynamic.(*Message).unmarshal at binary.go:154
github.com/jhump/protoreflect/dynamic.(*Message).UnmarshalMerge at binary.go:149
github.com/jhump/protoreflect/dynamic.(*Message).Unmarshal at binary.go:138
main.main at main.go:24
runtime.main at proc.go:203
runtime.goexit at asm_amd64.s:1373
 - Async stack trace
runtime.rt0_go at asm_amd64.s:220
```
[dynamicMessageTest.zip](https://github.com/jhump/protoreflect/files/4963125/dynamicMessageTest.zip)

**Comment by jhump** [comment]
Ugh. Yet another freakin' breakage in v1.4.0. Another case where v1.4 was _not_ backwards compatible with v1.3.5, despite only being a minor version change.

I think you'll have to change to use proto v1.3.5 in order to get this to work. I can provide a work-around for your particular code example. But I can't provide a robust fix -- they've basically changed the runtime so that many of the `proto` functions (like `Unmarshal` and `Marshal`) will no longer work with `*dynamic.Message` in 100% of cases :(

I'll see if I can upstream a fix to their project.

**Comment by jhump** [comment]
I'm very confused by this at the moment.

When I change my `go.mod` to point to protobuf v1.4.2, the `dynamic` package tests all pass and are green!

But as soon as I try to use a debugger to step through this very code (that _should_ fail the test), it does panic and fail! What the heck...

I'm basically trying to figure out how I could have learned of this issue sooner -- there are definitely users of v1.4.2 that also use protoreflect, and I'm trying to figure out how things are working. And figuring out why tests pass (even in CI, where there is a job that basically runs all tests against _latest_ of all dependencies) should have been a way to figure that out :/

**Comment by fooevr** [comment]
Yes, this is strange, It took me about twenty hours to locate the problem. Everything worked fine when I changed the version to protobuf 1.3.4. Thanks for your work, it helped me a lot in my project.

**Comment by jhump** [comment]
@fooevr, I now see what is going on.

I was wrong in my previous comment: v1.4.2 _is_ compatible with this part of my library.

I was obviously confused by this, too, since I saw the tests for this code pass but then the panic would occur only when trying to debug why it worked. But what's happening is that, yes, there is a panic there. But the proto runtime [recovers](https://github.com/protocolbuffers/protobuf-go/blob/d165be301fb1e13390ad453281ded24385fd8ebc/internal/impl/legacy_message.go#L106) from the panic and keeps going, after which things should work fine.

So I guess the more relevant question is, what is the behavior when you are _not_ debugging? Is a problem occuring?

**Comment by fooevr** [comment]
No abnormality was found when the service was running, but when I upgraded protoc-gen-go v1.4.1 library to generated new go code, it's dependency protobuf 1.4.1 to cause this problem. Now I have  downgraded protoc-gen-go to v1.2.3.

**Comment by jhump** [comment]
But what was the problem? You describe only seeing the panic when debugging. And I am pretty sure that is because you have your debugger set to break on all panics (even ones that will be caught/recovered). When _not_ debugging, what problem did you see?

**Comment by jhump** [comment]
After reproducing, I see this is not a real issue. The panic observed in the IDE is a _handled_ panic due to v1.4 of the protobuf runtime using the panic an a form of control flow/exception handling.

Resuming after the panic may not work, but due to a bug in the IDE/debugger:
https://youtrack.jetbrains.com/issue/GO-6191
https://github.com/microsoft/vscode-go/issues/2444
These issues are marked fixed, so you probably just need to update to the latest version. Looks like the underlying issue for both was a now-fixed bug in Delve (but the link I have to the issue does not work because delve changed ownership/organizations in GitHub).
