### ISSUE TITLE
Load service descriptor from generated package?

### ISSUE THREAD

**Issue by asutula** [jhump/protoreflect#344]
Amazing library with the promise to make implementing a gRPC relay layer so nice and clean. I guess this issue would be to report the lack of documentation or clarity about how to use some APIs that are hinted at in the README.

In the main README:

> ... you can also load descriptors for messages and services that are linked into the current binary. "What does it mean for messages and services to be linked in?" you may ask. It means your binary imports a package that was generated by protoc. When you generate Go code from your .proto sources, the resulting package has descriptor information embedded in it. The desc package allows you to easily extract those embedded descriptors.

I can't for the life of me figure out how to do this. I'd love to be able to create a service descriptor from generated go code.

**Comment by asutula** [comment]
I import [this](https://pkg.go.dev/github.com/textileio/powergate/ffs/rpc) package which includes protoc-generated code into my project, but it's not clear how to load that package into a service descriptor.

**Comment by jhump** [comment]
Did you look at the Go package doc? https://godoc.org/github.com/jhump/protoreflect/desc

The `Load*` functions are what you are looking for. Service descriptors are more buried, sadly, because the generated code does not explicitly register them, and the generated gRPC code tries to hide their details. So you can either use `LoadFileDescriptor` to load containing files by name, and dig out the service from there, or you can use the `grpcreflect` package: https://godoc.org/github.com/jhump/protoreflect/grpcreflect

The latter wants you to have access to a `*grpc.ServiceDesc`. There is one generated for each service, but it is not an exported symbol (so you can't access from outside the Go package). So the final way to access descriptors for these is to actually _register_ them (could be a dummy or nil implementation) with a gRPC server and then use `grpcreflect.LoadServiceDescriptors` (plural), which returns descriptors for all services registered in the server.

TBH, I think this is actually much easier using the new protobuf API in [google.golang.org/protobuf](https://github.com/protocolbuffers/protobuf-go/), which provides its own support for protobuf reflection. My library adds that support to the old protobuf API, so it is limited by what is already exposed by the old API. The new API is broader. A place to start looking would be the `FindDescriptorByName` method of `GlobalFiles` in `google.golang.org/protobuf/reflect/protoregistry`.

**Comment by asutula** [comment]
Thanks for the reply. That is useful information. I actually did make some good progress on figuring things out late last night. I ended up using the following pattern (errors ignored for simplicity here):

```
powConn, err := grpc.Dial(target, grpc.WithInsecure())
powStub = grpcdynamic.NewStub(powConn)

ffsDesc, err := desc.LoadFileDescriptor("ffs/rpc/rpc.proto")

ffsServiceDesc := ffsDesc.FindService("ffs.rpc.RPCService")
```

and then at a later point in a gRPC interceptor, I use the incoming request method name to query the service descriptor for the method descriptor of interest, then use the stub to execute the method request to the remote api... beautiful!

I think the root source of my confusion was I wasn't aware of the existence of the proto registry in go-grpc and how descriptors are registered in the registry and keyed by the path and filename of the source .proto file.

Additionally, the first the argument name to `desc.LoadFileDescriptor` is `filename`. I looked at your tests and saw `path/name.proto`, for example, passed in and it, combined with my lack of knowledge of the proto registry, gave me the impression that it was actually interacting with .proto files, which obviously doesn't work (and I read the docs that say the `protoparse` package does that, confusing me even more).

Anyway, this library is great. Thanks for making it. If you added a little contextual information to the README about the registry and maybe change that arg name to `registryFilenameKey` or something like that, I think it would save a lot of people a lot of time.

If you don't feel like doing that, or are open to a contribution there, let me know.

**Comment by jhump** [comment]
Doc patches welcome! Though I'd prefer meat like that go in the Go package doc instead of in the README. For readers of the README, maybe it just needs links to the Go doc (or to make existing link(s) more prominent). I do wish Go docs supported some sort of mark-up/hyper-linking... but despite that shortcoming, I still prefer that be the canonical source of info for how to use the APIs.
