### ISSUE TITLE
protoparse: custom options in descriptors are not marshaled to JSON

### ISSUE THREAD

**Issue by thetruechar** [jhump/protoreflect#352]
Proto file bar/foo.proto:
```proto
syntax = "proto2";
package bar;

import "google/protobuf/descriptor.proto";

extend google.protobuf.MessageOptions {
  optional string my_option = 51234;
}

message MyMessage {
  option (my_option) = "Hello world!";
  optional string barz = 1;
}

```
using protoparse:
```golang
func Test_ParseFiles(t *testing.T) {
	fds, err := protoparse.Parser{}.ParseFiles("bar/foo.proto")
	testutil.Ok(t, err)
	fdp := fds[0].AsFileDescriptorProto()
	bytes, err := protojson.Marshal(fdp)
	testutil.Ok(t, err)
	file, err := os.Create("bar_foo.json")
	testutil.Ok(t, err)
	_, err = file.Write(bytes)
}
```

final dfp, the option in MyMessage is empty:
```json
{
  "name": "bar/foo.proto",
  "package": "bar",
  "dependency": ["google/protobuf/descriptor.proto"],
  "messageType": [
    {
      "name": "MyMessage",
      "field": [
        {
          "name": "barz",
          "number": 1,
          "label": "LABEL_OPTIONAL",
          "type": "TYPE_STRING",
          "jsonName": "barz"
        }
      ],
      "options": {}
    }
  ],
  "extension": [
    {
      "name": "my_option",
      "number": 51234,
      "label": "LABEL_OPTIONAL",
      "type": "TYPE_STRING",
      "extendee": ".google.protobuf.MessageOptions",
      "jsonName": "myOption"
    }
  ]
}

```

**Comment by thetruechar** [comment]
The expected options might be like:

```json
          "options": {
            "[bar.my_option]": "Hello world!"
          }
```

**Comment by jhump** [comment]
@thetruechar: This is expected right now.

This repo has not yet been updated to make use of the API v2 (versions v1.4+ of github.com/golang/protobuf, v1.20+ of google.golang.org/protobuf). And the old API v1 had no "registry" types other than the global registries of statically known types and extensions. So it has to store unknown custom options as "unrecognized fields" in the resulting descriptor.

I have a [work-in-progress branch](https://github.com/jhump/protoreflect/tree/desc-wraps-protoreflect) that updates the repo in this direction. However, it is not ready to merge to master: though protoreflect's tests are green with that branch, there are some major downstream consumers that are broken by the change.

Note that writing to binary works fine, since that format understands and makes use of unrecognized fields. But for JSON, since it cannot fully interpret the fields, protojson cannot know how to marshal them.

**Comment by thetruechar** [comment]
Thanks for your reply @jhump .  I will check the new branch. I also notice that the [buf/protoencoding](https://github.com/bufbuild/buf/blob/master/internal/pkg/protoencoding/json_marshaler.go) do the similar things.
 My goal is to parse the proto files to json for further use(eg store in database), so I need to preserve all informations because maybe need reverse to proto files(consider using your protoprint) or generate language stubs.

Your mention that the binary works fine may also answer my puzzle that how generated pb.go stores the extension fields, I protojson.Marshal the pluginpb.CodeGeneratorRequest from protoc and found that the output is also missing the bar.my_option. And I don't import the generated pb.go the following codes still don't produce the bar.my_option option(but if I import, it will).
```golang
func file_bar_foo1_proto_rawDescGZIP() []byte {
	var file_bar_foo1_proto_rawDesc = []byte{
		0x0a, 0x0e, 0x62, 0x61, 0x72, 0x2f, 0x66, 0x6f, 0x6f, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
		// more bytes.... copy from pb.go ......................... 
	}
	return	protoimpl.X.CompressGZIP(file_bar_foo1_proto_rawDesc)
}

fd, _ := internal.DecodeFileDescriptor("foo", file_bar_foo1_proto_rawDescGZIP())
bytes, _ :=protojson.MarshalOptions{ }.Marshal(fd)
```
So there are 2 things I need to confirm here, first is the option is indeed embedded in the rawDesc bytes, but we can't marshal to json for the same reason you mentioned? Second is the pb.go init function protoimpl.TypeBuilder{}.Build do the magic things like type registry or so? 
Thanks in advance for your help!

**Comment by jhump** [comment]
> Your mention that the binary works fine may also answer my puzzle that how generated pb.go stores the extension fields, I protojson.Marshal the pluginpb.CodeGeneratorRequest from protoc and found that the output is also missing the bar.my_option

That's because unmarshaling, by default, only knows about extensions that are actually linked into your binary. To interpret other extensions, you need to use a resolver when unmarshaling.

Sadly, that means you need to do two passes when unmarshaling the descriptor protos:
1. Pass 1 does the unmarshaling and creates descriptors.
2. You then need to register all of these descriptors with a `protoregistry.Types`. That creates a resolver that knows about all extensions/custom options that are defined inside those files.
3. Pass 2 does the unmarshaling, but this time using the resolver created above. Now unmarshaling can successfully decode those custom options.

**Comment by jhump** [comment]
Note that you can also use the two-pass approach to successfully encode to JSON. The output of `protoparse`, currently, is a descriptor proto with unknown fields set.

But if you create a `protoregistry.Types` and register all output files with it, you can then re-load those descriptors (marshal and then unmarshal, using the resolver during the unmarshal step) and now they will emit to JSON as you want. This is because the unmarshaling step, combined with the resolver, will _recognize_ the custom options and interpret them.

**Comment by thetruechar** [comment]
Thanks, so you mean that I either use the two-pass approach or the new branch? I will try both lol. 
And the hard-to-understand pb.go init function's builder does a similar thing but use the GlobalTypes, do I understand correctly?

**Comment by jhump** [comment]
@thetruechar, I'm certain that it will work on the new branch. I was just linking to a work-in-progress "step in the right direction". I guess you could try it out and let me know! 😄

**Comment by jhump** [comment]
> And the hard-to-understand pb.go init function's builder does a similar thing but use the GlobalTypes, do I understand correctly?

More or less. It registers all descriptors in `GlobalTypes`, which is the default resolver used when unmarshaling.

**Comment by thetruechar** [comment]
@jhump  I tried the new branch(desc-wraps-protoreflect) using the same test code, the output is the same: no option emitted. And the two-pass approach works.

**Comment by thetruechar** [comment]
two-pass unmarshaling from custom option embedded json also worked, it need DiscardUnknown: true in first run, otherwise it will fail
```golang
	fd := &descriptorpb.FileDescriptorProto{}
	err := protojson.UnmarshalOptions{DiscardUnknown: true}.Unmarshal(readFromFile(t, "foo1.json"), fd)
	testutil.Ok(t, err)
	resolver, err := protoencoding.NewResolver(fd)
	testutil.Ok(t, err)
	err = protojson.UnmarshalOptions{Resolver: resolver}.Unmarshal(readFromFile(t, "foo1.json"), fd)
	testutil.Ok(t, err)
```
