### ISSUE TITLE
desc.CreateFileDescriptor not including well-known types, like google/protobuf/descriptor.proto

### ISSUE THREAD

**Issue by thetruechar** [jhump/protoreflect#362]
On other hand, protoparse.Parse will include well-known types, and LoadFileDescriptor is an internal method, so maybe it will be convenient desc.CreateFileDescriptor auto including well-known types.

**Comment by jhump** [comment]
The `protoparse` provides some well-known imports because it attempts to emulate `protoc`, which also does not require you provide your own sources for these well-known files (which are typically distributed _with_ `protoc`). So I don't think that is necessarily the right model for how the rest of the reflection API should work.

Also, I don't intend to augment the API of the `desc` package further, other than to improve interop with `google.golang.org/protobuf/reflect/protoreflect`. If you are writing new code that needs descriptors and reflection, you may try using that package instead as it is now provided by the standard protobuf Go runtime.

The future of this repo really just consists of more/better interop with the standard runtime packages. (You can get a preview of some of that in #354.) After that, I plan to eventually release a v2 that has neither a `desc` nor a `dynamic` package, as these are both provided by the standard runtime now. The other packages will have their API overhauled so they directly use the standard runtime descriptors and reflection APIs, not `desc`.

In the standard Go runtime, what you are trying to do is straight-forward. The API to create a new file descriptor is `protodesc.NewFile` and instead of explicitly providing a list of descriptors for the dependencies, you provide a resolver. If you provide `protoregistry.GlobalFiles`, you'll get the behavior you describe, where dependencies will be satisfied using the versions of files that are linked into the program.
