### ISSUE TITLE
protoparse: 1.8.0 may have stopped parsing trailing comments correctly

### ISSUE THREAD

**Issue by lukesneeringer** [jhump/protoreflect#371]
I get a unit test error on the [api-linter](https://github.com/googleapis/api-linter) Renovate upgrade to 1.8.0. The failing test is [here](https://github.com/googleapis/api-linter/pull/717/checks?check_run_id=1512185850).

I have started investigating and I _think_ that protoparse has had a subtle change in behavior in how it parses trailing comments (my best guess is that it stopped parsing them at all, but I am not sure).

Still need to look into it more on my end, but I got far enough that it seemed like filing this was appropriate.

**Comment by jhump** [comment]
Trailing comments are still there, so I'll definitely need more details to understand what's happening.

There's a test case for source code info, which includes trailing comment info, that uses test proto files and "golden outputs". And the outputs didn't change with newer code, at least not for the test files I'm using. So maybe there's something peculiar about your test files?

https://github.com/jhump/protoreflect/blob/master/desc/protoparse/test-source-info.txt

**Comment by lukesneeringer** [comment]
Thanks, I will look into it more and get back to you. Definitely strange. :)

**Comment by apasel422** [comment]
It does appear that something changed here.

Compare `1.7.1` and `1.8.0` with the following proto source:

```proto
// before
message Book {}
// after
```

`1.7.1`:
```
+    Leading comments:
+ before
```

`1.8.0`:
```
+    Leading comments:
+ before
+
+    Trailing comments:
+ after
```

**Comment by jhump** [comment]
I have reproduced this. It looks like it happens only at the end of the file (so last element in the file) and only if there are no detached/subsequent comments.

**Comment by jhump** [comment]
I'm not sure why I changed the EOF symbol from a rune to an identifier, but that was the problem:
https://github.com/jhump/protoreflect/commit/ed9aaa29021f1e512473097669860e793d29f630#diff-34f7a550abeab015586f34f301aa3c1266f4be02d6aa882f8fae0d55e80e28e4R212

Because of the node type being an identifier (which really makes no sense), the logic decides that the final trailing comment _should_ be considered a leading comment for that identifier, not a trailing comment for the previously lexed token. So this little change broke this. PR coming up in a sec...

**Comment by jhump** [comment]
I just made a v1.8.1 release that includes this fix.

**Comment by lukesneeringer** [comment]
Thanks @jhump (also, you found the problem before I had a chance to follow up, so double thanks!)
