### ISSUE TITLE
Question: convenience functions for reflecting on options

### ISSUE THREAD

**Issue by chrisnovakovic** [jhump/protoreflect#377]
Let's say I have the following proto source file:

```
syntax = "proto3";

package mwe;

import "google/api/annotations.proto";

service TestService {
    rpc Test(Request) returns (Response) {
        option (google.api.http) = {
            get: "/test"
        };
    };
}

message Request {}
message Response {}
```

What's the most straightforward way to enumerate the `Test` method's options, given the `FileDescriptor` for this file? I'm looking to extract the field number, the FQDN of the option, and some information about the message representing the option's value (e.g. for this proto, it'd be ideal if I could identify that `get` is specified in the `google.api.HttpRule` and then extract its value). Clearly the information is available somewhere because the `protoparse` and `protoprint` packages can combine to round-trip a proto perfectly, but after looking at `protoprint/print.go` in depth, it seems that many of the auxiliary functions are internal, so I can't use them directly. Inspired by the discussion in #352, I also tried using `protojson` and the `desc-wraps-protoreflect` branch of `protoreflect`, but the options are missing in the output from that too. Is there a simple way to do this that I'm just not seeing?

**Comment by jhump** [comment]
If the options are not linked into your binary (e.g. the corresponding protos that contain the options are compiled to Go and those Go packages imported by your program), then they will be stored as "unrecognized" fields in the descriptor.

If you have a `desc.FileDescriptor`, with the options unrecognized, you can do a round-trip of marshalling and unmarshalling in order to interpret them. Or you can convert the descriptor protos to dynamic messages and inspect them that way.

For the latter, you would first create a `dynamic.ExtensionRegistry` and then register the file(s) you want to examine using its [`AddExtensionsFromFileRecursively`](https://godoc.org/github.com/jhump/protoreflect/dynamic#ExtensionRegistry.AddExtensionsFromFileRecursively) method. You can then use this registry to call [`dynamic.AsDynamicMessageWithExtensionRegistry`](https://godoc.org/github.com/jhump/protoreflect/dynamic#AsDynamicMessageWithExtensionRegistry) to convert one of the descriptor protos or options messages into a `*dynamic.Message`. This then provides plenty of API for examining all of the fields, including custom options.

The former approach, round-trip serialization, requires using some functionality in the new Go protobuf runtime/API:

1. Marshal the descriptors to bytes -- transitively, so including all dependencies. This can be done easily using [`desc.ToFileDescriptorSet`](https://godoc.org/github.com/jhump/protoreflect/desc#ToFileDescriptorSet) and then using `proto.Marshal` to serialize that.
2. Create a new [`protoregistry.Files`](https://godoc.org/google.golang.org/protobuf/reflect/protoregistry#Files) and register all of the files with it. Unfortunately, to do this, you'll have to first convert the files to the new API's version of a descriptor. But this isn't too bad if you use the `FileDescriptorSet` created in the above step. (Code snippet below.)
3. Unmarshal the bytes created in step 1, but using the resolver created in step 2. This means you need to use [`proto.UnmarshalOptions`](https://godoc.org/google.golang.org/protobuf/proto#UnmarshalOptions) with the `Resolver` field set to the `Files` instance created above. This will allow all of the custom options to be successfully interpreted as the bytes are unmarshaled. Use this `UnmarshalOptions` instance to unmarshal the bytes into a `FileDescriptorSet`.
4. Now you can turn the `FileDescriptorSet` from the above step into `desc.FileDescriptor` values that have the options of interest (e.g. using [this method](https://godoc.org/github.com/jhump/protoreflect/desc#CreateFileDescriptorsFromSet)). You can use the `GetOptions()` method of the descriptors to access the options protos. And now you can use the `ProtoReflect()` method on these values to examine all fields, including the custom options (which will be extension fields -- i.e., the `IsExtension()` method on the corresponding [`FieldDescriptor`](https://godoc.org/google.golang.org/protobuf/reflect/protoreflect#FieldDescriptor) will return true).

```go
// register entries in FileDescriptorSet with protoregistry.Files
var files protoregistry.Files
for _, fd := range fileSet.File {
    d, err := protodesc.NewFile(fd, &files)
    if err != nil {
        panic(err) // TODO: handle error
    }
    if err := files.RegisterFile(d); err != nil {
        panic(err) // TODO: handle error
    }
}
```

**Comment by chrisnovakovic** [comment]
Thanks for the detailed (and fast!) response, @jhump.

I've opted for the former approach, but ran into difficulty at step 3 - it seems that `protoregistry.Files` doesn't implement the interface required for `Resolver`. `protoregistry.Types` does, though...

```go
// step 1:
fileSet := desc.ToFileDescriptorSet(fd...)
fileSetBytes, err := proto.Marshal(fileSet)
if err != nil {
    panic(err)
}

// step 2:
var files protoregistry.Files
for _, fd := range fileSet.File {
    d, err := protodesc.NewFile(fd, &files)
    if err != nil {
        panic(err)
    }
    if err := files.RegisterFile(d); err != nil {
        panic(err)
    }
}

// step 3:
var fullFileSet *descriptorpb.FileDescriptorSet
err = proto.UnmarshalOptions{
    /*
    cannot use files (type protoregistry.Files) as type interface { FindExtensionByName(protoreflect.FullName) (protoreflect.ExtensionType, error); FindExtensionByNumber(protoreflect.FullName, protowire.Number) (protoreflect.ExtensionType, error) } in field value:
        protoregistry.Files does not implement interface { FindExtensionByName(protoreflect.FullName) (protoreflect.ExtensionType, error); FindExtensionByNumber(protoreflect.FullName, protowire.Number) (protoreflect.ExtensionType, error) } (missing FindExtensionByName method)
    */
    Resolver: files,
}.Unmarshal(fileSetBytes, fullFileSet)
if err != nil {
    panic(err)
}

// step 4:
fullfds, err := desc.CreateFileDescriptorsFromSet(fullFileSet)
if err != nil {
    panic(err)
}
```

**Comment by jhump** [comment]
> it seems that `protoregistry.Files` doesn't implement the interface required for `Resolver`. `protoregistry.Types` does, though

Ah, yes. My bad. I referenced the wrong one. So I think you have to actually use both: the `Files` is so that you can build all of the file descriptors, passing `&files` to the `protodesc.NewFile` function. And then you also need to accumulate all of the files in a `Types` instance, for resolving extensions in the unmarshal step.

**Comment by chrisnovakovic** [comment]
> > it seems that `protoregistry.Files` doesn't implement the interface required for `Resolver`. `protoregistry.Types` does, though
> 
> Ah, yes. My bad. I referenced the wrong one. So I think you have to actually use both: the `Files` is so that you can build all of the file descriptors, passing `&files` to the `protodesc.NewFile` function. And then you also need to accumulate all of the files in a `Types` instance, for resolving extensions in the unmarshal step.

Indeed, and that's how I ended up solving it - I've added the working code in comment 2. Thanks again for the advice!
