### ISSUE TITLE
Crash in protoparse.Parser.ParseFiles with field options

### ISSUE THREAD

**Issue by apasel422** [jhump/protoreflect#380]
Unfortunately I don't have a readily reproducible test case that works outside Google, but the API Linter is encountering crashes in `protoparse.Parser.ParseFiles`, seemingly when a `FileDescriptorSet` loaded by the linter contains a `FieldOptions` extension, the linter itself depends on the Go package corresponding to that same extension, and the proto file being parsed uses the extension on a field. I suspect that somehow the two are conflicting, perhaps as a result of the global state that the Go proto package initializes.

The gist of the set-up is as follows:

`my_ext.proto` compiled as a `FileDescriptorSet`:
```proto
syntax = "proto2";
package my_ext;
import "google/protobuf/descriptor.proto";
message Foo {
  optional bool x = 1;
}
extend google.protobuf.FieldOptions {
  optional Foo foo = 1234;
}
```

`my_msg.proto` parsed with `protoparse`:
```proto
syntax = "proto2";
package my_msg;
import "my_ext.proto";
message MyMsg {
  optional int32 a = 1 [(my_ext.foo) = { x: true }];
}
```
The issue seems to only happen when the Go binary doing the parsing itself depends on `my_ext_go_proto`, though the setup is different enough inside and outside Google that I'm not completely sure about this.

The resulting stack trace is something like:
```
reflect.Value.Type(0x0, 0x0, 0x0, 0x5559835041ce, 0x8)
        src/reflect/value.go:1919 +0x189
protoreflect/dynamic/dynamic.(*Message).mergeInto(0xc00058d410, 0x7f42a6fe7240, 0xc0006e0e60, 0x7f42a6fe7201, 0xc0006e0e60, 0xc0006e0e60)
        protoreflect/dynamic/dynamic_message.go:2218 +0x408
protoreflect/dynamic/dynamic.mergeVal(0x5559835efd40, 0xc00058d410, 0x16, 0x5559835e7560, 0xc00012d7f0, 0x196, 0x555983495401, 0x0, 0x0)
        protoreflect/dynamic/dynamic_message.go:2434 +0x876
protoreflect/dynamic/dynamic.(*Message).mergeInto(0xc00058d170, 0x555983612400, 0xc0005df6b0, 0x1, 0x0, 0xffffffffffffffff)
        protoreflect/dynamic/dynamic_message.go:2294 +0x15fd
protoreflect/dynamic/dynamic.(*Message).ConvertToDeterministic(0xc00058d170, 0x555983612400, 0xc0005df6b0, 0x0, 0x0)
        protoreflect/dynamic/dynamic_message.go:2079 +0xa5
protoreflect/desc/protoparse/protoparse.interpretOptions(0xc000494750, 0x7f42a6fe5918, 0xc0005c7e80, 0x555983612400, 0xc0005df6b0, 0xc00012cdf0, 0x1, 0x1, 0xffffffffffffffff, 0x0, ...)
        protoreflect/desc/protoparse/options.go:997 +0xb09
protoreflect/desc/protoparse/protoparse.interpretFieldOptions(0xc000494750, 0x55598361c1e0, 0xc0005c7e80, 0x1, 0x8)
        protoreflect/desc/protoparse/options.go:827 +0x6aa
protoreflect/desc/protoparse/protoparse.interpretMessageOptions(0xc000494750, 0x55598361d840, 0xc0005c4a50, 0x1, 0x0)
        protoreflect/desc/protoparse/options.go:743 +0x706
protoreflect/desc/protoparse/protoparse.interpretFileOptions(0xc000494750, 0x55598361e640, 0xc000123960, 0x26, 0xc00067eda0)
        protoreflect/desc/protoparse/options.go:694 +0xe5
protoreflect/desc/protoparse/protoparse.(*linker).linkFiles(0xc0004a8980, 0xc0004a8980, 0x1, 0x1)
        protoreflect/desc/protoparse/linker.go:67 +0x1b4
protoreflect/desc/protoparse/protoparse.Parser.ParseFiles(0xc0001cfba0, 0x1, 0x1, 0x0, 0xc00031ce40, 0x0, 0x0, 0x1, 0xc0005af360, 0x0, ...)
        protoreflect/desc/protoparse/parser.go:231 +0x2e5
main.(*cli).lint(0xc000261290, 0xc00052cae0, 0x555983c27278, 0x1, 0x0, 0x0, 0x0)
        api_linter/cmd/api_linter/cli.go:153 +0x427
main.runCLI(0xc000032110, 0x3, 0x3, 0x0, 0x0)
        api_linter/cmd/api_linter/main.go:44 +0x85
main.main()
        api_linter/cmd/api_linter/main.go:37 +0x6a

panic: reflect: call of reflect.Value.Type on zero Value
```

I'm trying to get more details.

**Comment by jhump** [comment]
Hmmm, that is very odd. I wonder if that means that invariants have been broken in the protobuf runtime. It seems like that should not be possible.

On line 2205, we call `proto.GetProperties(reflect.TypeOf(pm).Elem())`. It should probably be re-written to just call `proto.GetProperties(target.Type())`, which is what this call should amount to (lines 2292-2295).

And yet the resulting properties indicate a property with a name that does not match any field on the target type.

Maybe you could run this in a debugger and set a breakpoint there, and examine the type of `pm` and the values in `prop`? I think that would shed more light on this.

For what it's worth, I do have a branch that I've been meaning to merge soon that would almost certainly address this. In #354, the `protoparse` package gets a pretty major overhaul (as do _many_ things actually) and uses the new runtime's `dynamicpb` package instead of this repo's `dynamic` package.

**Comment by apasel422** [comment]
Thanks for the quick response. I'll work on getting the debugger output for you, but I did add some logging to the `dynamic` package at one point and was surprised to see the reflected type show up as `my_ext_go_proto.Foo` in the output instead of something like `dynamic.Message`.

**Comment by jhump** [comment]
> was surprised to see the reflected type show up as `my_ext_go_proto.Foo`

If you mean the type in those `reflect.Value` variables, that is expected. This step in `protoparse`, which is interpreting custom options, is converting a generated type (e.g. `*my_ext_go_proto.Foo`) to a `*dynamic.Message`. This is done because the older Go protobuf runtime had no notions of dynamic extension registries (for interpreting/creating custom options that were not compiled by protoc and linked into the calling program). So the only way to generate and interrogate custom options is to convert to a dynamic message and back.

**Comment by apasel422** [comment]
At the point of the crash `target` has no field called `X` in the output of:

```go
f := target.FieldByName(prop.Name)
if !f.IsValid() {
  var fs []string
  target.FieldByNameFunc(func(f string) bool {
    fs=append(fs,f)
    return false
  })
  log.Info(fs)
}
```
The output is:
```
[state x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 x13 x14 unknownFields sizeCache]
```

**Comment by apasel422** [comment]
OK, after doing some more digging internally, I think this is an internal-only issue related to the proto API migration currently going on. I'll post back here with more once I confirm.

**Comment by jhump** [comment]
Whew... I was about to say that something sounds seriously wrong. We shouldn't have gotten a property named `X` if the corresponding type has no such field. Maybe something is haywire in the `protoc-gen-go`-generated `init` functions that register the types? IIRC, that code should be populating the registry (including that set of properties) using reflection, which is why we shouldn't ever observe a mismatch like this.

**Comment by apasel422** [comment]
Let me just say that patching the `reflect` package is dark magic. Closing for now.
