### ISSUE TITLE
File Descriptor comparison

### ISSUE THREAD

**Issue by lukesneeringer** [jhump/protoreflect#388]
Howdy,
I am about to write some code that I need internally to take two file descriptors and compare them, and provide messages / fields / services / etc. that are added, modified, or removed.

I am planning on having it be a separate library, but I wanted to offer to PR it in here instead if it is something you want.

**Comment by jhump** [comment]
That sounds pretty cool -- maybe a `protodiff` package? Although before I offer to accept and maintain it, I'd be interested if you could sketch the API out a little further, like describing key types and function signatures.

**Comment by lukesneeringer** [comment]
Sure. How about I put the proof-of-concept code up on GitHub in a private repo and invite you to it? Even if you decide that you do not want it, you might still have useful ideas. :-)

**Comment by lukesneeringer** [comment]
Incidentally, my having-written-no-code plan for an API is something like a `Differ` struct that has an `old` and `new` FileDescriptor.

I am still trying to get a handle on what I think the methods should be. One idea is to have an Added/Modified/Removed for each descriptor type, e.g.

```go
interface Differ {
  AddedMessages() []*desc.MessageDescriptor
  ModifiedMessages() []*desc.MessageDescriptor
  DeletedMessages() []*desc.MessageDescriptor
  // ...and so on

  // This would allow for an agnostic variant also...
  AddedDescriptors() []desc.Descriptor
  ModifiedDescriptors() []desc.Descriptor
  DeletedDescriptors() []desc.Descriptor
}
```

But that feels like a lot of methods to call for a full comparison. Another option is having just one method per type (e.g. `.Messages()`) that returns a wrapper that includes both the descriptor and what happened.

There's at least one other question here, which is overlapping diffs. For example, if a field is added to a message, should that show up in _both_ "modified messages" _and_ "added fields"? For my purposes (CI), the answer is probably no. But others may have different needs.

**Comment by jhump** [comment]
If adding/modifying a field does not count as modifying a message, what does? Just options? What about differences in reserved ranges and extension ranges?

I can definitely see why nested message/enum/extension differences, on the other hand, would not count as the enclosing message being changed.

I like the idea of mirroring the descriptor hierarchy, like `FileDiff`, `MessageDiff`, etc. However it may need to change to "flatten" the hierarchy a bit -- such that top-level (i.e. at the file-level) message accessors get all messages -- not just direct children of the file, but those nested inside of other messages, too.

So the hierarchy would be much flatter:
* `FileDiff`: can report diffs on syntax, package, and imports, in addition to child descriptors
    * `MessageDiff`: can report diffs on extension ranges and reserved ranges/names
        * `FieldDiff`
        * `OneofDiff`: can report diffs on constituent fields
    * `EnumDiff`
        * `EnumValueDiff`
    * `ServiceDiff`
        * `MethodDiff`

All `*Diff` types can report differences on options. I suspect it should omit reporting differences on some synthetic entries, like map-entry messages and proto3-optional oneofs.

Also, we'd need to be clear on "identity" -- how do we know two messages are intended to be the same, for purposes of reporting a messages as "modified" as opposed to both one added and one removed? I assume we'd use names for messages, enums, services, and methods but numbers for fields and enum values (though enums with aliases could throw a wrench into that -- maybe enum value number + ordinal for those?)

Does that seem like it's pushing in the right direction?

**Comment by lukesneeringer** [comment]
> If adding/modifying a field does not count as modifying a message, what does?

Well, the original idea I had was that this counted as an added _field_, and I did not want to send "two positives". As I have started working on this, I think sending two positives is correct, mostly because I started making them more hierarchical (e.g. a changed MessageDiff might have an added FieldDiff).

> I can definitely see why nested message/enum/extension differences, on the other hand, would not count as the enclosing message being changed.

Ditto comments, which sometimes are interesting and sometimes are not. Same for locations.

> So the hierarchy would be much flatter:

This is where I started going before reading this, which seems like a good indicator that it is a good approach.

> Also, we'd need to be clear on "identity" -- how do we know two messages are intended to be the same, for purposes of reporting a messages as "modified" as opposed to both one added and one removed?

I was thinking of names for everything, but I think your idea of numbers where available and names otherwise is probably a better one.

**Comment by lukesneeringer** [comment]
Incidentally, I have started getting some [preliminary code on paper](https://gist.github.com/lukesneeringer/80e3dd84724d8fbf1190c516b5b79e01), and I think I like the overall interface and think it will scale reasonably well.

Right now what I have in mind is:

- There is a `Differ` for each type (file, message, etc.), which always has an `Equal` method and may have various other methods for drilling down (e.g. `FileDiffer.DiffMessages`).
- The `Equal` method and the drill-down methods all accept flags that indicate what to ignore, e.g. `IgnoreComments` ignores comment diffs. The drill-down methods only provide differs that are unequal.
- I can provide methods for any other type of difference where it is non-trivial to test. I do not think `DiffName` is valuable, but not all comparisons are easy.

Would love to get your thoughts. If this is something you think will help the project, I will build it as a PR into protoreflect. If it is more work than it is worth, I'll do it off to the side.

**Comment by lukesneeringer** [comment]
@jhump Any thoughts on this? If you are generally happy with the interface, I will flesh out the remainder of the implementation and send a PR.

**Comment by lukesneeringer** [comment]
> Also, we'd need to be clear on "identity" -- how do we know two messages are intended to be the same, for purposes of reporting a messages as "modified" as opposed to both one added and one removed?

Having gotten to fields, I think the best way is to have a `DiffFieldsByNumber` and `DiffFieldsByName` on the MessageDiffer object, and let the user decide. This is consistent with how you approach finding fields in `desc.MessageDescriptor`.

**Comment by jhump** [comment]
Hey, @lukesneeringer, I think that API is coming along. I do have some questions/comments about it.

Also, as this is taking a little more shape, I'm thinking maybe it's too high-level to maintain protoreflect. Although I am still happy to provide input if you care for it and think it's a cool idea.

Here are some things I noticed in the gist:
* I had some naming nits, for clarity -- like `DiffExtension`, which is actually look at extensions on the descriptor _options_, is probably better named `DiffCustomOptions`. Also, it has a different "shape" for the API, taking a single extension to compare instead of returning diffs for all extensions present in either side.
* The choice of a goroutine and channel in `DiffMessages` seem like overkill. They introduce complexity and new failure modes -- like resource leaks if the caller does not exhaust the channel. This would then call for the use of `context.Context`, which could be cancelled by the caller and signal the goroutine to abort. However, this API doesn't feel worth all of that ceremony: why not just return `[]*MessageDiffer` instead? Is it really important to parallelize the consumption of diffs with the computation of those diffs? (Most protobuf schemas are simple enough that the work being doing in parallel to compare objects is rather trivial.)
* Speaking of eagerly analyzing, I'm wondering if it would make more sense to do an eager analysis in `NewFileDiffer`. As it is, every invocation of `Equals` or call to recurse into a child object must repeat work. So actually examining an entire hierarchy could end up doing a lot of repeated work for the leaves. Maybe instead the options should be passed to the `New*Differ` constructors, and the analysis could be done eagerly and then memoized.

**Comment by lukesneeringer** [comment]
Thanks, these are all good suggestions. And based on the high level point, I will do the work in its own Go module.

**Comment by lukesneeringer** [comment]
Closing this issue as we decided to use a separate module for this purpose.
