### ISSUE TITLE
Working example. Question.

### ISSUE THREAD

**Issue by m1ome** [jhump/protoreflect#39]
Hey, 
First of all, you do a great job with this library, thanks!

I have one question about working example. Let's say I have only `.proto` file, can I send a message to a gRPC service using your library? Without generating code go `.pb.go` files?

I just can't understand stuff related to `FileDescriptor`.
Can you provide some example?

**Comment by jhump** [comment]
Hi, @m1ome,
The library cannot do anything directly with `.proto` files. You need descriptor protos. The easiest way to create a descriptor proto from the `.proto` file is to use `protoc`:

```
protoc --descriptor_set_out=./descriptors.protoset \
    --include_source_info --include_imports -I. \
    test.proto
```

Something like that will produce a file named `descriptors.protoset`. This is a set of descriptors -- a representation of the `.proto` source, but in the format of a [descriptor proto](https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto#L55).

You can then unmarshal the contents of this file into a `FileDescriptorSet` with code along the lines of [this example](https://github.com/jhump/protoreflect/blob/master/internal/testprotos/desc_test1_protoset.go#L14) (note that the `descriptors.protoset` file will *not* be gzipped; the example uses gzip because the embedded blob in that file is compressed).

With that, you can use `desc.CreateFileDescriptorFromSet(...)` to get the `*desc.FileDescriptor` that corresponds to your original `test.proto` file.

If you are doing this to invoke a method on a GRPC server, it would be easier if you have the server expose the reflection service. For a Go GRPC server, you just call `reflection.Register(svr)` when your server is starting ([source](https://github.com/grpc/grpc-go/blob/master/reflection/serverreflection.go#L64)). Then you can use the [grpcreflect](https://godoc.org/github.com/jhump/protoreflect/grpcreflect#NewClient) package to construct descriptors in your client that are downloaded from the server (e.g. the server can describe itself and send its descriptor protos to the client via GRPC).

FWIW, I have a `grpcurl` command-line tool that I wrote for work that provides a simple command-line interface for invoking GRPC methods dynamically. It allows users to pass JSON data on the command-line that then get converted into GRPC request messages. I have not yet open-sourced that, but I am planning to. (As you can guess, it makes *heavy* use of this `protoreflect` repo. In fact it uses all four packages: desc, dynamic, grpdynamic, and grpcreflect.)

**Comment by m1ome** [comment]
@jhump thank you for your answer. Seems in your tool you generating this descriptors protoset file on the fly? Do you know can this be done not through `system exec`, through `protoc`?

**Comment by jhump** [comment]
> Seems in your tool you generating this descriptors protoset file on the fly?

I'm not sure I understand. The tool does *not* currently generate the descriptor set on the fly.

> Without protoc dependency using proto-gen-go ?

That's not going to work I'm afraid. All `protoc-gen-go` does is take the descriptor set and generate Go code.  The tool that actually parses `*.proto` source files into descriptor protos is `protoc` itself.

I am not aware of any pure-go library that can parse protos into descriptors. But it may be possible to compile `libproto` into a static library and then link to it  and make calls into it from Go code using cgo.

**Comment by jhump** [comment]
@m1ome, can I close this issue? Or do you have any follow-up questions I can help with?

**Comment by jhump** [comment]
@m1ome. I'm going to go ahead and close this issue. If you have more questions, just re-open it.

**Comment by jhump** [comment]
@m1ome, I've been hacking this thing into shape to do what you are asking -- to be able to do proto reflection *without* having encoded descriptors, but just having sources (e.g. no need to first run `protoc`).

Take a look at #46: it adds a new `github.com/jhump/protoreflect/desc/protoparse` package that lets you create descriptors from `*.proto` source files. I think I have it nearly ready to use. I've got test cases that verify it generates descriptors that are effectively the same as `protoc`, using a reasonably wide range of input files that exercise all features of the proto IDL.

**Comment by m1ome** [comment]
@jhump ok i will look at it! Awesome news!

**Comment by jhump** [comment]
@m1ome, I've merged that branch. So you can now load descriptors from proto source files. Note that you must have *all* necessary sources available. E.g. if the file you want to load has `import` statements, you must also be able to supply sources for those imported files (and so on and so forth if those files also have `import` statements).
