### ISSUE TITLE
Protoparse option to provide alias names for imports

### ISSUE THREAD

**Issue by weeco** [jhump/protoreflect#391]
Hey!

I'd like to parse multiple proto files that may use each other as dependency. All proto files are stored in a central schema registry (e.g. the one from Confluent) and unfortunately they are not stored like you'd do it on a filesystem. Instead they are stored in JSON objects like this and do not really have an absolute path that can be used for looking it up as dependency:

```json
    {
        "subject": "owlshop-orders",
        "version": 1,
        "id": 100012,
        "schemaType": "PROTOBUF",
        "references": [
            {
                "name": "customer.proto", // This is the import as used in the proto schema
                "subject": "owlshop-customers", // This is the name to the schema as stored in the schema registry, basically the alias
                "version": 1
            }
        ],
        "schema": "syntax = \"proto3\";\npackage fake_models;...."
    },
```

So the problem I have here is that I have multiple imports that may be used with different "aliases". I want to parse the schemas using `protoparse.Parser` which does a nice job resolving the dependencies. I just have to take care that I do not try to parse any schema twice as this would result in duplicate symbol errors like this:

> duplicate symbol fake_models.Customer.version: already defined as field in \"customer.proto\

I could pass a `LookupImport` func into the parser, but that func requires a FileDescriptor to be returned which would basically send me to the dependency hell again, because my dependencies may have other dependencies with different alias names. If protoparse had an option to register a schema that may be imported by a set of aliases that would make my life much easier I believe? For example:

```go
		schemasByPath["owlshop-customers"] = "proto3;...."
		importAliases["owlshop-customers"] = []string{"customer.proto", "customers.proto"}
		parser := protoparse.Parser{
			Accessor:              protoparse.FileContentsFromMap(schemasByPath),
			InferImportPaths:      true,
			
			ValidateUnlinkedFiles: true,
			IncludeSourceCodeInfo: true,
			ErrorReporter:         errorReporter,
		}
		descriptors, err := parser.ParseFiles(filePaths...)
```

What do you think? Maybe there's an existing simple solution which is not on my radar currently?

**Comment by jhump** [comment]
I think you are going to run into serious issues linking descriptors if you have the same descriptor that can be referenced in multiple ways.

No protobuf runtime really supports that, and that includes `protoparse`. The issue is that file imports are _nominal_ -- a file descriptor actually embeds the import paths of its dependencies, and these are then used to find those dependencies and link all symbols.

So even if protoparse could help you with your aliases (which I think you could implement on your own in a custom file accessor), the resulting descriptors may fail to link. I don't even think protoparse could link them, even with the help of a custom file accessor for resolving sources.

**Comment by weeco** [comment]
Okay makes sense to me. Thanks for your response 👍
