### ISSUE TITLE
enum GetInputType is enum name not value

### ISSUE THREAD

**Issue by clpluie** [jhump/protoreflect#409]
pb as below:
enum ModuleType {
    MODULE_ANDROID_TEST = 0;
    MODULE_TEST = 1;
}
message HelloRequest { 
  	    ModuleType module = 1;
} 

call req : HelloRequest{module:0}

decode req ：func GetInputType => HelloRequest{module:MODULE_ANDROID_TEST}

**Comment by jhump** [comment]
@pluie-cloud, I don't understand what the problem is. Could you provide a code example or more details on what you are trying to do and what APIs in protoreflect you are using?

**Comment by pluie-cloud** [comment]
> @pluie-cloud, I don't understand what the problem is. Could you provide a code example or more details on what you are trying to do and what APIs in protoreflect you are using?

when i use a proto with enum type data，i flect byte to proto , except  value of enum not name. HelloRequest{module:0} is my except not HelloRequest{module:MODULE_ANDROID_TEST}

**Comment by jhump** [comment]
I repeat: what were you trying to do and what protoreflect APIs were you using?

Are you using the dynamic package and are seeing that it formats/prints the message different than you expect? Also, why do you expect to see a numeric representation of the enum instead of the name? Is this causing an actual problem in your program?

**Comment by pluie-cloud** [comment]
> I repeat: what were you trying to do and what protoreflect APIs were you using?
> 
> Are you using the dynamic package and are seeing that it formats/prints the message different than you expect? Also, why do you expect to see a numeric representation of the enum instead of the name? Is this causing an actual problem in your program?

ths for reply, 
my program can't recognized the name. is there any good solution for me

this is my basic info : version is 1.9.0, 
code:
func (c *pbCodec) DecodeInput(methodName, serviceName *string, data []byte) (interface{}, error) {
...
methodDesc, ok := descriptor.(*desc.MethodDescriptor)
		if !ok {
			return errors.New("not methodDescriptor")
		}
d, err := c.unmarshalMessage(methodDesc.GetInputType(), data)
...
}

**Comment by jhump** [comment]
Where is `data` coming from in that code example? Is that not the request data that is causing you problems? I still don't understand enough of what you are doing. And I also still don't know what APIs in this repo (what package/function) that you are using that you think is giving you the wrong data.

**Comment by clpluie** [comment]
What I am doing now is to convert binary and struct to each other. When I try to parse binary according to struct, I will read the name of enum instead of value，

**Comment by jhump** [comment]
You still haven't told me what you are doing to format things, such that they emit a name instead of a value. Are you calling `.String()` on something and expecting it to show you a number instead of a name?

So you call `desc.MethodDescriptor.GetInputType()`. That gives you back a `desc.MessageDescriptor`. Then what? Can you not just provide the full source (or a repro case), including a `fmt.Print...` for what you are seeing (that you're expecting to be different)?
