### ISSUE TITLE
version incompatiable

### ISSUE THREAD

**Issue by magicdvd** [jhump/protoreflect#422]
dynamic.Message doesn't implement the ProtoReflect (interface proto.Message)

The problem is proto.Message version.

Could you help upgrade  from old
"github.com/golang/protobuf/proto" 
to 
new "google.golang.org/protobuf/proto" 

and implement the functions.

**Comment by jhump** [comment]
Hi, @magicdvd,
Here are a couple of observations that should help you:
1) The new `google.golang.org/protobuf` runtime packages (API "v2") include support for descriptors and dynamic messages. So, depending on what you are needing to accomplish, you may not actually need to use this repo. Consider using [`google.golang.org/protobuf/types/dynamicpb`](https://pkg.go.dev/google.golang.org/protobuf/types/dynamicpb) instead of the `dynamic` package in this repo.
2) Inter-op between old and new runtimes is provided by the protobuf runtime itself. To adapt a `*dynamic.Message` to the newer `proto.Message` interface, import `"github.com/golang/protobuf/proto"` (the older API) and use the [`proto.MessageV2`](https://pkg.go.dev/github.com/golang/protobuf/proto#MessageV2) function therein:

```go
import protov1 "github.com/golang/protobuf/proto"
import "github.com/jhump/protoreflect/dynamic"
import "google.golang.org/protobuf/proto"

func dynamicToNewMessage(msg *dynamic.Message) proto.Message {
    return protov1.MessageV2(msg)
}
```
