### ISSUE TITLE
protoprint unusual output

### ISSUE THREAD

**Issue by vtolstov** [jhump/protoreflect#435]
i'm try to write simple format tool for proto. And have strange results
simple example https://play.golang.org/p/S4fsTngwqjh
source proto file https://github.com/unistack-org/micro-tests/blob/master/server/http/proto/test.proto

i want only indent properly, but as i see output contains empty lines between message fields, options does not contains ; char. Also i don't understand why options converted to form like
```
option (micro.openapiv3.openapiv3_operation) = { operation_id:"Call" parameters:<parameter:<name:"Clientid" in:"header" required:true schema:<schema:<type:"string">>>> parameters:<parameter:<name:"Csrftoken" in:"cookie" required:true schema:<schema:<type:"string">>>> responses:<default:<reference:<_ref:".test.Error">>> };
```

**Comment by jhump** [comment]
> i'm try to write simple format tool for proto.

Descriptors are not a good source for doing formatting. And `protoprint` was _not_ designed for re-formatting files. The main issue is that descriptors are _lossy_: the structure of some things (like options and extension ranges) is not perfectly preserved and a descriptor can also lose comments that were present in the source file (depending on exactly where the comment appears). On top of that, `protoprint` intentionally has very few options for formatting (no control over line length limits, where to put curly braces, where to insert newlines, how/whether to do column alignment, etc).

> empty lines between message fields

The printer doesn't provide very much control over newlines. Look at the Go docs for more info. In particular, the `Compact` field on `Printer` describes what you're seeing (a newline between every descriptor element) and a way to turn it off (though it might start dropping newlines that you'd prefer to keep, such as between messages).

> options does not contains ;

It definitely has trailing semicolons. Even your example contains one. Do you have an example where you see it missing? More importantly: can you compile the output with `protoc`? (If so, then it is eliding a semicolon that is not actually necessary. The descriptor does not have enough info to capture superfluous semicolons in your source file.)

> i don't understand why options converted to form like

Because the descriptor is lossy. There is not enough info in the descriptor to know what your original option statements looked like. So instead of trying to guess how you may have de-structured a message across multiple options, it just puts them all in one.

**Comment by jhump** [comment]
For a formatter, you probably want to work with an AST, not a descriptor. Take a look at https://pkg.go.dev/github.com/jhump/protoreflect@v1.10.1/desc/protoparse#Parser.ParseToAST

There is a `Print` function, but it prints what was parsed, and it doesn't provide APIs to really modify the API like a formatter would. The expectation for a formatter would be to instead walk the AST and then adjust whitespace and print as it goes. (If you look at the impl for `Print` it's very simple.)

**Comment by vtolstov** [comment]
Thank you!
