### ISSUE TITLE
protoparse: optional colons in options

### ISSUE THREAD

**Issue by WillAbides** [jhump/protoreflect#451]
In an option message with a list value, the colon between the name and the opening `[` is optional according to protoc. protoparse requires the colon be present.

For example all of the below are valid in protoc but only the first two are valid in protoparse:

```protobuf

// valid in both
option (opt) = {m: [{key: "a",value: {}}]};

// valid in both
option (opt) = {m: []};

// valid in protoc only
option (opt) = {m [{key: "a",value: {}}]};

// valid in protoc only
option (opt) = {m []};
```

I will create a PR for this.

**Comment by jhump** [comment]
This totally makes sense that the colon would be optional, just like if the next character is a brace `{` or angle bracket `<`.

I also need to update a [grammar doc](https://github.com/jhump/protocompile/tree/master/grammar) I recently wrote to include this change.

**Comment by jvolkman** [comment]
This issue is actually a bit more complex. The colon is only optional if the value type is a repeated message. e.g.,
```
  foo [1, 2, 3]
```
will not compile, but
```
  foo [{}, {}]
```
will. Same rules apply to empty lists: the colon is only optional before `[]` if the value is a message type.

See also: https://github.com/jvolkman/intellij-protobuf-editor/blob/master/core/src/main/java/idea/plugin/protoeditor/lang/annotation/PbTextAnnotator.java#L194-L213

Arguably it'd be more productive to submit a PR and fix protoc than to codify this insanity in a spec.
