### ISSUE TITLE
protoparse:  can't get field options info after ParseFiles

### ISSUE THREAD

**Issue by zyuanyuz** [jhump/protoreflect#453]
proto file content:
```
...
import "vaidate.proto";
message UpdateHelpInfoRequest {
  string app_id = 1 [ (validate.rules).string = {min_len : 1, max_len : 128} ];
}
...
```
validate.proto content:
```
...
// Validation rules applied at the field level
extend google.protobuf.FieldOptions {
    // Rules specify the validations to be performed on this field. By default,
    // no validation is performed against a field.
    optional FieldRules rules = 1071;
}
...
```
And then I call ParseFiles:
```
fds, err := protoParser.ParseFiles(protoFileName)
```
Now I got `fds` as `[]*desc.FileDescriptor`,there is `Options` in `fds[0].messages[0].fields[0].proto`,but missing specific information like`(validate.rules).string = {min_len : 1, max_len : 128}`.

![image](https://user-images.githubusercontent.com/29815126/140450578-eea4ccc4-c0e8-47ff-8620-1bf0c7a118e9.png)

Is there any way I can get the `fieldOptions` info after `ParseFiles`? thanks!

**Comment by jhump** [comment]
This package still uses the V1 API of the protobuf runtime for Go. In that, there is now way to access extensions (which is what custom options are) that are not known at compile-time for the processing program. And protoparse is looking at definitions in source code it compiles, not looking at compile-time-registered extensions.

So the custom options are represented as unknown fields. You have a couple of options:
1. If these custom options _are known_ to your program at compile-time, then you can simply marshal the options message to bytes and then back into an options message.
    * This will cause the protobuf runtime to unmarshal these bytes into the known extensions. (You then use the `proto` package API to interact with the extension fields.)
2. If the options are not known at compile time, you can use the V2 API, which allows you to provide a custom resolver during unmarshaling, for extensions not known at compile time.
    * You'll need to create a [`*protoregistry.Types`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protoregistry#Types) and register all extensions defined in the just-parsed descriptors.
    * This, unfortunately, requires translating `*desc.FileDescriptor` values to `protoreflect.FileDescriptor` values. And once you have these, you'll have to recursively register extensions from these file(s) since the V2 API doesn't really include any useful helpers to just register everything for you.
    * You can then marshal the options message to bytes and unmarshal, using that registry as a resolver in `proto.UnmarshalOptions`. You can then interact with the extensions using the API in the `proto` package or via the new support for reflection.
3. You can use a dynamic message. This repo contains an implementation of a dynamic message and extension registry that work with the old V1 API.
    * Create a [`*dynamic.ExtensionRegistry`](https://pkg.go.dev/github.com/jhump/protoreflect/dynamic#ExtensionRegistry) and use `AddExtensionsFromFileRecursively` to populate it.
    * Create a new `*dynamic.Message` using the descriptor for the options message in question and the above created registry.
    * Now you can call `msg.ConvertFrom` to convert your options message _into_ the dynamic message, which will use the extension registry to interpret those unknown fields.
    * Now you can use the API provided by the `*dynamic.Message` to interact with the extensions.

Sorry this is so convoluted. The cause is two-fold:
1. I wrote this whole repo back in the days of API V1, which had zero support for descriptors, runtime extensions and type resolvers, and dynamic messages. So there's some aspect of "jumping through hoops" to get all of this functionality to work with those old APIs.
2. Even the new API V2 is missing a lot of utility/helper functions that would simplify this.

FWIW, I have an in-progress arc of work on a "next generation" of protoparse, and it _does_ work with API V2 and should not have this same issue. If you want to try it out, it's called [protocompile](https://pkg.go.dev/github.com/jhump/protocompile): https://github.com/jhump/protocompile. Warning: it's API is rather different from `protoparse` -- mostly an improvement in abstractions and performance. But it may take a little re-writing to port your code over to it.

**Comment by cardistry** [comment]
I have the same problem, can you give some code cases ?

**Comment by jhump** [comment]
@cardistry, if you look at the current release candidate ([v1.15.0-rc1](https://github.com/jhump/protoreflect/releases/tag/v1.15.0-rc1)), it no longer stores custom options in unknown fields. I think it may have the functionality you are looking for. Can you try it out?

Note that custom options will be represented **dynamically**, using the extension definitions that were in the source that was compiled. So if you are trying to access them using a _generated_ extension, you may have some issues:
```go
val := proto.GetExtension(pkgpb.E_MyCustomOption)
msg, ok := val.(*pkgpb.MyCustomMessage)
```
The above example would be problematic. In particular, if the extension's type is a _message_, you will not be able to type-assert the value to a generated type, because the actual runtime type of the message will be `*dynamicpb.Message`.

In order to convert that to a generated type, you'd need to `proto.Marshal` the dynamic message to bytes and then `proto.Unmarshal` into an instance of the generated type:
```go
data, _ := proto.Marshal(val.(proto.Message))
msg := &pkgpb.MyCustomMessage{}
_ = proto.Unmarshal(data, msg)
```

Note that even the above technique could have issues, such as if the source that you just compiled contained a definition of the custom option that is _incompatible_ with what was used to generate your Go code (e.g. whatever was used to generate `pkgpb` in the examples above).

I hope that all makes sense.
