### ISSUE TITLE
[help] How to send a custom response through stream.SendMsg

### ISSUE THREAD

**Issue by ngxlua** [jhump/protoreflect#465]
I tried to send a custom response using protoreflect, but failed:

```
body, _ := dynamic.NewMessage(descriptor.GetOutputType()).MarshalJSONPB(&jsonpb.Marshaler{})
if err := stream.SendMsg(body); err != nil {
    return status.Errorf(codes.Internal, "failed to send message: %s", err)
}
```

error msg:
```
{
  "error": "13 INTERNAL: Failed to parse server response"
}
```

How not to load proto file and can dynamically return the response, I hope to get help, thank you

**Comment by ngxlua** [comment]
I noticed that github.com/jhump/protoreflect/tree/master/dynamic/grpcdynamic encapsulates the method of sending requests, but it makes a real request to GRPC's server through request.

I want to bypass the request to the server and directly construct the return response.

**Comment by 89z** [comment]
Can you share your message definition? I might be able to help

**Comment by jhump** [comment]
@ngxlua, what is the context? Is this a normal gRPC server, but you are trying to use a dynamic message response instead of a generated message? If so, why (I ask because there may be other ways to accomplish what you're trying to achieve)? The error looks like the message type you sent is not valid for the message type that the client is expecting. Are you sure you used the correct descriptor?

**Comment by ngxlua** [comment]
@89z 
@jhump 

Thank you for your reply. It is no problem now. After I `MarshalJSONPB`, I did not convert it to binary data, so after sending it to the client, an error occurred.
