### ISSUE TITLE
How to get custom extension without generating dynamically (i.e. without .pb.go files)?

### ISSUE THREAD

**Issue by phye** [jhump/protoreflect#467]
Per protobuf golang [doc](https://developers.google.com/protocol-buffers/docs/reference/go-generated#extensions) below, if I were'to get extension option dynamically, I need to have `extpb.E_SingularInt32` which will only be generated in .pb.go files. 

``` protobuf
extend Foo {
  optional int32 singular_int32 = 1;
  repeated bytes repeated_string = 2;
  optional Bar repeated_message = 3;
}
```
``` go
m := &somepb.Foo{}
proto.SetExtension(m, extpb.E_SingularInt32, int32(1))
proto.SetExtension(m, extpb.E_RepeatedString, []string{"a", "b", "c"})
proto.SetExtension(m, extpb.E_RepeatedMessage, &extpb.Bar{})

v1 := proto.GetExtension(m, extpb.E_SingularInt32).(int32)
v2 := proto.GetExtension(m, extpb.E_RepeatedString).([][]byte)
v3 := proto.GetExtension(m, extpb.E_RepeatedMessage).(*extpb.Bar)
```
How can I use this package to achieve that without having to generate .pb.go?

**Comment by jhump** [comment]
You no longer need to use this repo for that. As of API v2 (packages in "google.golang.org/protobuf", whereas v1 is in "github.com/golang/protobuf"), there is support for descriptors and dynamic types in the main protobuf runtime.

You'll have to get a hold of a descriptor for the extension. This repo could still be useful for that -- the "desc/protoparse" package lets you parse protobuf source code and get descriptors, and the "desc/builder" provides an API for building descriptors programmatically. But the path to convert from this repo's descriptors to the official types (in "google.golang.org/protobuf/reflect/protoreflect") is unfortunately not very straight-forward. I can post a code snippet if you need.

Once you have a `protoreflect.ExtensionDescriptor`, you can use it and the new proto reflection API to set extension fields on a message. One nasty caveat: I think the `protoreflect.Message.Set` method complains if the `ExtensionDescriptor` used does not also implement `ExtensionTypeDescriptor`. So, for that, you can use `dynamicpb.NewExtensionType` to create an `ExtensionType` and calls its `TypeDescriptor` method.

**Comment by phye** [comment]
Thanks for the response!

I'll follow your idea and see if I can achieve that.

**Comment by phye** [comment]
I've tried it out, however I still cannot catch the point.

Here's how I do it:

Given the following proto
```
package hello;
option go_package="github.com/phye/hello";
extend google.protobuf.EnumValueOptions {
   string msg = 50001;
}

message MyEnum {
    Invalid = 0;
    Hello = 1 [msg="HelloWorld!"];
}
```

```go
fds, _ := protoparse.Parser{...}.ParseFiles("hello.proto")
f := fds[0]
// Need to get APIv2 protoreflect.FileDescriptor from dpb.FileDescriptorProto
// FIXME(phye): Can I pass FileDescriptorProto from desc to protoreflect/protodesc???
fd_v2, _ := protodesc.NewFile(f.AsProto().(*dpb.FileDescriptorProto), protoregistry.GlobalFiles)
o := fd_v2.Enums().Get(0).Values.Get(0).Options()
et := dynamicpb.NewExtensionType(fd_v2.Extensions().Get(0))

expect := proto.GetExtension(o, et) 
// Exptected expect is "Hello", however I only got empty string
```

Is it due to the FIXME part I mentioned above?

**Comment by phye** [comment]
Any updates here?

**Comment by jhump** [comment]
That code looks mostly right. The issue is admittedly confusing. When I run the program (after fixing a few things in the source proto), I get the following output (I assume you get the same):
```
EnumOption is 50001:"HelloWorld!"
ExtensionType is {desc:{ExtensionDescriptor:0xc000380000}}
Expect is: 
```

We can see from the first line that the options do contain the extension. But notice the use of a tag number instead of a field name -- that's because this value is stored in the message's _unrecognized properties_. That's because that extension (50001) is not known by the V1 APIs at runtime. (And, even if they were, the registered extension may not match the one parsed, so protoparse always stores custom option values as unrecognized fields -- this ensures they don't interact incorrectly with compiled-in extension definitions and the proto can still correctly be serialized.)

Another trick here is the fact that the file that _defines_ the extension and the file that _uses_ it (that includes a custom option using that extension) are one and the same. That means you must re-parse the file -- basically, you want to re-unmarshal the proto in a way that unmarshaling _recognizes_ the 50001 extension tag.

To do this, you'll need to take a few steps:
1. Create a new `protoregistry.Types`; let's call it `typeReg`.
2. After you get the `et`, the extension type, register it: `typeReg.RegisterExtension(et)`
3. Now you can marshal the file descriptor proto to bytes.
4. Then you re-_unmarshal_ the file descriptor proto to bytes, but this time use `typeReg` as the resolver in your unmarshal options.
5. You don't have to re-create a full descriptor from the resulting unmarshaled proto. You can just dig out the relevant options method from the proto itself.
6. This time, the options will include your custom option as recognized. So the last line will work.

I know this seems a bit silly. But, sadly, there's actually no way around it for files that both define an extension and use it -- the first time you unmarshal it, the extension isn't recognized. You then have to turn around use that file (which defines the extension) to unmarshal it again, so the extension is recognized the second time.

Unfortunately, some awkwardness is due to protoparse using the API v1, in that even if you separated the files (so the option is defined in one file an then used in another), you'd still have to re-marshal the proto. However, that should be remedied I think in an upcoming re-do of protoparse that uses the v2 protobuf APIs (https://github.com/jhump/protocompile).

**Comment by phye** [comment]
> That code looks mostly right. The issue is admittedly confusing. When I run the program (after fixing a few things in the source proto), I get the following output (I assume you get the same):
> 
> ```
> EnumOption is 50001:"HelloWorld!"
> ExtensionType is {desc:{ExtensionDescriptor:0xc000380000}}
> Expect is: 
> ```
> 

Ah, sorry, I do missed pasting the entire .proto file, however, you got my point :)
Indeed, I got the same output as you pasted above.

> We can see from the first line that the options do contain the extension. But notice the use of a tag number instead of a field name -- that's because this value is stored in the message's _unrecognized properties_. That's because that extension (50001) is not known by the V1 APIs at runtime. (And, even if they were, the registered extension may not match the one parsed, so protoparse always stores custom option values as unrecognized fields -- this ensures they don't interact incorrectly with compiled-in extension definitions and the proto can still correctly be serialized.)

This is exactly what I observed: the extension can be correctly serialized, but I can't get the extension value by myself. With your explanation above, I think I knows the meaning of **API** more correctly this time ---- I **was** thinking that the difference on lies in concrete types, such as `desc.FieldDescriptor` and `protoreflect.FieldDescriptor`, but the `dpb.FileDescriptorProto` ought to be compatible. 

> 
> Another trick here is the fact that the file that _defines_ the extension and the file that _uses_ it (that includes a custom option using that extension) are one and the same. That means you must re-parse the file -- basically, you want to re-unmarshal the proto in a way that unmarshaling _recognizes_ the 50001 extension tag.
> 
> To do this, you'll need to take a few steps:
> 
> 1. Create a new `protoregistry.Types`; let's call it `typeReg`.
> 2. After you get the `et`, the extension type, register it: `typeReg.RegisterExtension(et)`
> 3. Now you can marshal the file descriptor proto to bytes.
> 4. Then you re-_unmarshal_ the file descriptor proto to bytes, but this time use `typeReg` as the resolver in your unmarshal options.
> 5. You don't have to re-create a full descriptor from the resulting unmarshaled proto. You can just dig out the relevant options method from the proto itself.
> 6. This time, the options will include your custom option as recognized. So the last line will work.
> 
> I know this seems a bit silly. But, sadly, there's actually no way around it for files that both define an extension and use it -- the first time you unmarshal it, the extension isn't recognized. You then have to turn around use that file (which defines the extension) to unmarshal it again, so the extension is recognized the second time.

This is **exactly** the detailed steps I want, much appreciated!
As a programmer, I can understand the difficulties to achieve same user experience when APIs below are completely different. Hence the detailed steps above is actually not silly to me, but acceptable as I'm just trying to implement tool(which only needs to run once), hence duplicated marshal/unmarshal is completely acceptable. 

> 
> Unfortunately, some awkwardness is due to protoparse using the API v1, in that even if you separated the files (so the option is defined in one file an then used in another), you'd still have to re-marshal the proto. However, that should be remedied I think in an upcoming re-do of protoparse that uses the v2 protobuf APIs (https://github.com/jhump/protocompile).

I've heard this repo in several issues, hope I can use it a.s.a.p :)

Again, thanks for this wonderful package and the detailed explanation, I learned quite a lot.
