### ISSUE TITLE
Get the comment content of the field ？

### ISSUE THREAD

**Issue by sswanv** [jhump/protoreflect#469]
Hello, I want to generate some related auxiliary code by reading the proto file. There is a requirement to get comments, but no relevant content is found. Does the current version provide relevant support?

**Comment by jhump** [comment]
Yes, there is a way to get comments. Every descriptor in the `desc` package has a `GetSourceInfo()` method which can return span information (the location of the element in the original source) and comments.

However, this information is not present in descriptors that are compiled into a Go binary. So if you use `desc.LoadMessageDescriptor`, nothing will be present. This is because `protoc-gen-go` strips source info from the descriptors in order for the resulting generated code and binaries to be smaller.

But if you are already planning on reading proto files, you should be good. If you use `protoc`, and then open the resulting file descriptor set, you must remember to supply the `--include_source_info` flag, so this information (span/location info and comments) is added to the result. If you use the `desc/protoparse` package in this repo,  you will similarly need to set the `IncludeSourceCodeInfo` field to true on the `protoparse.Parser`.
