### ISSUE TITLE
Remove unused imports from built descriptor

### ISSUE THREAD

**Issue by devnev** [jhump/protoreflect#504]
I'm trying to write a protoc plugin that may remove some elements from a proto and then output a new proto file. In the process, some of the imports may become unused, but at the moment such imports are left in the output. From reading the protoreflect source, it looks like `FileBuilder.FromFile` is adding all imports to the explicit import list, and then `FileBuilder.Build` adds all those imports regardless of whether they're still referenced.

## Observed behaviour

```go
func main() {
  descs, _ := protoparse.Parser{}.ParseFiles(os.Args[1:])
  for descIdx, fileDesc := range descs {
    fileBuilder, _ := builder.FromFile(fileDesc)
    // some arbitrary code that removes elements, e.g.
    fileBuilder.RemoveMessage("InternalMessage")
    descs[descIdx], _ = fileBuilder.Build()
  }
  protoprint.Printer{}.PrintProtosToFileSystem(descs, "out")
}
```

```proto
syntax = "proto3";
package demo;
import "google/protobuf/empty.proto";
message InternalMessage {
  google.protobuf.Empty empty = 1;
}
```

The above code will produce a proto file something like

```proto
syntax = "proto3";
package demo;
import "google/protobuf/empty.proto";
```

## Desired behaviour

Some way to have the resulting proto stripped of the unused `empty.proto` import.

**Comment by jhump** [comment]
When you create a new builder from a file, all of the imports are preserved in order for custom options to remain known. This was done in #228 in order to fix #227.

I think I have an idea on a way to change the current implementation so that existing file imports are not explicitly added (meaning they can be automatically pruned) while also preserving add'l info so that we don't have a regression of the bug linked above.
