### ISSUE TITLE
Dynamic message is not convertible to proto.Message

### ISSUE THREAD

**Issue by nikunjy** [jhump/protoreflect#511]
```
import "google.golang.org/protobuf/proto"

dyn := dynamic.NewMessage(something)
var msg proto.Message = dyn // This will fail 
```

This is because it is not compatible with the new proto package "google.golang.org/protobuf/proto"
I think it is missing a `ProtoReflect` method 

I can do a PR but I might not know enough.

**Comment by nikunjy** [comment]
I think you will just have to add a `ProtoReflect` method

**Comment by jhump** [comment]
This repo targets the older version of the API. It implements `proto.Message` if you import `"github.com/golang/protobuf/proto"` instead of the newer `"google.golang.org/protobuf/proto"`.

In order to convert from the interface defined in that older package to the newer interface, use the [`MessageV2`](https://pkg.go.dev/github.com/golang/protobuf/proto#MessageV2) function.

**Comment by nikunjy** [comment]
I see. I didn't see that function. Thanks @jhump
