### ISSUE TITLE
programmatic access to message option's value

### ISSUE THREAD

**Issue by nordicdyno** [jhump/protoreflect#516]
After ParseFiles I can see a (custom) message string option and it's value when call String() on *MessageDescriptor, but don't get how to access value of this option in message. Can you help, please? I'm a newbie in proto files parsing and API looks a bit tricky.

**Comment by nordicdyno** [comment]
code sample in sake of clarity: https://go.dev/play/p/nkb9ABOuH5D

I can see `options:{50206:"my_option_value"}` in output and really want to understand how to access to this value from code. :)

**Comment by jhump** [comment]
The message descriptor struct has a field named `Options`. The custom option (an extension defined with tag 50206) is an _extension_ on this value.

However, `protoparse` actually stores custom options as unknown values so that they can be marshaled to bytes deterministically (gross, I know). So, sadly, to _interpret_ those unknown bytes, you have to marshal the `MessageOptions` to bytes and unmarshal back into a value. Then you can use the [`proto.GetExtension`](https://pkg.go.dev/github.com/golang/protobuf/proto#GetExtension) function to query for the value. You could also use the reflection capability of the new runtime (the message's `ProtoReflect()` method) to inspect the fields.

When you compiled (generated Go code) for the place where that extension is defined, it will result in a package variable named like `E_<name>`. For example:

```proto
extend google.protobuf.MessageOptions {
    string my_option = 50206;
}
```
Will result in a var named `E_MyOption` in the Go code.

You can use that var (an "extension description") along with `proto.GetExtension` as the easiest way to read that value.

If the extension in question has not been compiled to Go code, then it's unfortunately trickier. First you have to get descriptors for all extensions of interest. You need to put them into a `*protoregistry.Types`, and then use that registry as a [Resolver](https://pkg.go.dev/google.golang.org/protobuf@v1.28.0/proto#UnmarshalOptions) when you do the above suggested step of unmarshalling the options from bytes.

Unfortunately, this repo still leans on the "v1" of the protobuf runtime API (in "github.com/golang/protobuf"). I do have a work in progress that will hopefully be complete soon that will use the newer v2 API (in "google.golang.org/protobuf"). But, until then, if your extension descriptors are `*desc.FieldDescriptor` (from this repo), such as if the extensions of interest are _in the file you just parsed_., you have to do some legwork to convert the `*desc.FileDescriptor` to a `protoreflect.FileDescriptor`. You have to recursively convert the `*desc.FileDescriptor` and all of its dependencies using `protodesc.NewFile`. The `Resolver` argument to that function must include all of the file's imports. You use a `*protoregistry.Files` as the resolver: first convert the "leaves" (file that have no imports) and register them in that registry. Then you can use that registry to convert the others, "up the stack" in a recursive solution (e.g. after a file's imports have all been registered, you can then convert that file).

Sorry this is complicated. A new version of this library will help simplify a lot, but I've been on a sabbatical for a few months, so progress on that new thing was put on pause.

I have also been meaning to overhaul this library to have better interop with the v2 API (which also would help a lot). I've had a lot of this stuff in progress for a long time (for example #354) and haven't had the opportunity to complete that work.

**Comment by jhump** [comment]
@nordicdyno, closing this. If the above doesn't help or you have more questions, feel free to re-open.
