### ISSUE TITLE
 LoadMessageDescriptorForMessage bug 

### ISSUE THREAD

**Issue by Shukla-Ankur** [jhump/protoreflect#528]
I have encounetered following bug while using Confluent-kafka-go v1.9.2 which uses this package. 
jhump/protoreflect v1.12.0
Confluent-kafka-go v1.9.2

I am running a grpc server in go language. The APIs are defined using protobuf.
Clients send data in a generic API where input object is defined as:

```
message Document {
    DocumentMeta meta = 1;
    bytes data = 2;
    google.protobuf.Any details = 3;
}
```

The details field uses Any type so that clients can send any type of message using this API. On server-side, the .proto files are used to register Message types

```
protoFile, err := ioutil.ReadFile(tmp_file)
pb_set := new(descriptorpb.FileDescriptorSet)
if err := proto.Unmarshal(protoFile, pb_set); err != nil {
			return err
	}
pb := pb_set.GetFile()[0]
fd, err := protodesc.NewFile(pb, protoregistry.GlobalFiles)
msgType = dynamicpb.NewMessageType(fd.Messages().Get(0))
protoregistry.GlobalTypes.RegisterMessage(msgType)

```
The types get registered successfully and I can check them.

`desc.LoadMessageDescriptorForMessage(msg) ` step fails with error
`error interface conversion: *dynamicpb.Message is not desc.protoMessage: missing method Descriptor`
msg of type protoV1.MessageV1 is derived from a protoreflect.ProtoMessage.

How to reproduce
Run the above steps, it can be deterministically reproduced.

1.     Create an API with Any type field
2.     Create a proto file on client-side,
3.     server will use the proto file from client to register message descriptors
4.     Client will use proto file to send data via above API
5.     On server-side, Unmarshal the data from Any field like anypb.UnmarshalNew(doc.GetDetails(), proto.UnmarshalOptions{})
6.     run desc.LoadMessageDescriptorForMessage(msg)

**Comment by jhump** [comment]
@Shukla-Ankur, FYI, there is a big "Note" on the main README for this repo that this was implemented against the "v1" of the protobuf runtime (in "github.com/golang/protobuf" import paths).

The `dynamicpb` package is in the "v1" of the runtime (in "google.golang.org/protobuf" import paths). The two are not entirely compatible.

You might _try_ using [`proto.MessageV1`](https://pkg.go.dev/github.com/golang/protobuf/proto#MessageV1) (in the "v1" APIs), but I don't know if that will work. (Even if the function returns something, vs. blowing up at the sight of a dynamic message, it still may not work with this repo.)

The `desc.LoadMessageDescriptorForMessage` is expecting a _generated_ message struct, not a dynamic message (though it will work correctly if you instead using the dynamic message implementation in this repo, in "github.com/jhump/protoreflect/dynamic").

**Comment by Shukla-Ankur** [comment]
To rectify the issue, I tried the following changed approach:
1. Use msgregistry.MessageRegistry to register descriptors since this uses V1 Message type. 
```
  ty := fds[i].GetMessageTypes()[0]
url := msgR.ComputeURL(ty)
msgR.AddMessage(url, ty)
```
2. Unmarshal using above registry. This should give MessageV1 types
`msgR.UnmarshalAny(doc.GetDetails())`

This resolves the above error. 

3. However, if I convert this V1 message to V2 type, and pull out parent descriptor using `protoMsg.ProtoReflect().Descriptor().Parent()` parent is nil. During registration, the parent of the message was NOT nil.

During registration, I captured the following details. 
url : `type.googleapis.com/com.test.abcd.pb.cat.Cat`, 
MessageDescriptor: `name:"Cat"  field:{name:"name"  number:1  label:LABEL_OPTIONAL  type:TYPE_STRING  json_name:"name"}  field:{name:"id"  number:2  label:LABEL_OPTIONAL  type:TYPE_INT64  json_name:"id"}  field:{name:"breed"  number:3  label:LABEL_OPTIONAL  type:TYPE_STRING  json_name:"breed"}`
parent: `name:"/Users/testuser/Go/src/github.com/test/EventBus/protos/events/EventV1.proto"  package:"com.test.abcd.pb.cat"  message_type:{name:"Cat"  field:{name:"name"  number:1  label:LABEL_OPTIONAL  type:TYPE_STRING  json_name:"name"}  field:{name:"id"  number:2  label:LABEL_OPTIONAL  type:TYPE_INT64  json_name:"id"}  field:{name:"breed"  number:3  label:LABEL_OPTIONAL  type:TYPE_STRING  json_name:"breed"}}  options:{go_package:"github.com/abcd/abcd/pb/cat"}  syntax:"proto3"`

 I have 2 ways to unmarshal Any- using protoregistry or msgregistry.MessageRegistry. 1st one uses V2 types and 2nd uses V1 types. jhump/protoreflect likes to use V1 type, so msgregistry should be preferred.

**Comment by jhump** [comment]
> Regarding your suggestion on using github.com/jhump/protoreflect/dynamic

The `msgregistry` package should automatically do this if the given type URL is not a compile-time known message type.

> However, if I convert this V1 message to V2 type, and pull out parent descriptor ...

I have no idea about this. The actual descriptor you get back from `desc.LoadMessageDescriptorForMessage` for the resulting message certainly _does_ have a file descriptor parent. I'm not sure if this is a bug with the `MessageV2` function or perhaps you are assuming the conversion will try to retain more than it does. Why do you need the file?

Maybe we can back up a little: why do you need to use `LoadMessageDescriptorForMessage` at all? If you are using the v2 APIs, just use their descriptor functionality as well. This repo was designed before the v2 API existed and is meant to be used with the v2 API. Is there something else in this repo you are trying to use that requires the use of `desc.Descriptor` instead of `protoreflect.Descriptor`?

While there is a plan to migrate this repo to a v2, which will directly support and interop with the new APIs, that v2 will _not_ include the descriptor and dynamic message functionality (since that is now handled by the protobuf runtime API).

**Comment by Shukla-Ankur** [comment]
Actually this is the implementation within Confluent-kafka-go. I am attaching the below snippet from that repo. If you look at the switch case, this code expects protoreflect.ProtoMessage type, then uses desc.LoadMessageDescriptorForMessage() by converting the Message to v1. 

```
func (s *Serializer) Serialize(topic string, msg interface{}) ([]byte, error) {
	if msg == nil {
		return nil, nil
	}
	var protoMsg proto.Message
	switch t := msg.(type) {
	case proto.Message:
		protoMsg = t
	default:
		return nil, fmt.Errorf("serialization target must be a protobuf message. Got '%v'", t)
	}
	autoRegister := s.Conf.AutoRegisterSchemas
	normalize := s.Conf.NormalizeSchemas
	fileDesc, deps, err := s.toProtobufSchema(protoMsg)
	if err != nil {
		return nil, err
	}
	metadata, err := s.resolveDependencies(fileDesc, deps, "", autoRegister, normalize)
	if err != nil {
		return nil, err
	}
	info := schemaregistry.SchemaInfo{
		Schema:     metadata.Schema,
		SchemaType: metadata.SchemaType,
		References: metadata.References,
	}
	id, err := s.GetID(topic, protoMsg, info)
	if err != nil {
		return nil, err
	}
	msgIndexBytes := toMessageIndexBytes(protoMsg.ProtoReflect().Descriptor())
	msgBytes, err := proto.Marshal(protoMsg)
	if err != nil {
		return nil, err
	}
	payload, err := s.WriteBytes(id, append(msgIndexBytes, msgBytes...))
	if err != nil {
		return nil, err
	}
	return payload, nil
}
```

This code does not work with protoregistry.GlobalTypes.RegisterMessage(msgType) since it converts Any to dynamicpb.Message, but does work until GetID() with messageRepository.AddMessage() since this converts Any to MessageV1.

**Comment by jhump** [comment]
It might be better off to expand the `switch` to support both the V1 and V2 versions of `proto.Message` and convert the other direction: use `proto.MessageV2`. With the V2 API, there is no need to use `desc.LoadMessageDescriptorForMessage` at all; use `msg.ProtoReflect().Descriptor()` instead. Then you're working with the V2 APIs model of a descriptor instead of the one in this repo, but it should not be difficult to modify logic to work with that model instead of this one. I think that will be the most robust way to deal with this.

**Comment by Shukla-Ankur** [comment]
ok, so I need to update the confluent's SDK and basically understand the usage for V2 type's descriptors. Thanks
