### ISSUE TITLE
can not FindMessage from linked files

### ISSUE THREAD

**Issue by TeavenX** [jhump/protoreflect#565]
### platform
darwin/arm64

### question
I have two proto files, `B.proto` is imported by `A`, but when I try to call FindMessage to get a message in `B` which used in `A`, it return nil.
```shell
> ls
A.proto  B.proto  pbrf.go
```
```proto
// A.proto
syntax = "proto2";
package A;
import "B.proto";

service ServA {
  rpc Call(B.MsgInB) returns(B.MsgInB);
}
```
```proto
// B.proto
syntax = "proto2";
package B;

message MsgInB {
  optional int64 unm = 1;
}
```

```go
p := protoparse.Parser{
  ImportPaths: []string{"./"},
}
fds, err := p.ParseFiles("a.proto")
fd := fds[0]
println(fd.GetServices()[0].GetMethods()[0])
msg := fd.FindMessage("B.MsgInB")
println(msg)
symbals  := reflect.ValueOf(fd).Elem().FieldByName("symbols")
println(symbals)
```
msg is always nil, but `B.MsgInB` is already linked, output:
```shell
[name:"B.proto"  package:"B"  message_type:{name:"MsgInB"  field:{name:"unm"  number:1  label:LABEL_OPTIONAL  type:TYPE_INT64  json_name:"unm"}}]

<nil>

map[ServA:0x140000a8000 ServA.Call:0x140000a8050]
```
I think message symbol in B is not related to FileDescriptor

**Comment by jhump** [comment]
@TeavenX, this is working as intended. The `FindMessage` method of `*desc.FileDescriptor` searches only the given file for the message. It does not search its imports.

You could recursively crawl through the files imports (and their imports possibly -- depending on if you want to search the entire transitive graph or not) and call `FindMessage` on each one to find it.

Also, the protoparse package has been effectively replaced by [protocompile](https://github.com/bufbuild/protocompile). I'm working on a v2 of this repo and it will not included protoparse; users should instead migrate to the protocompile module.

In the protocompile module, what you're looking for does in fact exist: you can use `linker.ResolverFromFile` on one of the `linker.File` instances returned from compilation. That will find any symbol that is _visible_ to the file. So, in your example, the symbol `B.MsgInB` is _visible_ to `A.proto` because it imports `B.proto`, so it would successfully find the symbol.

**Comment by TeavenX** [comment]
Thanks for reply, that helps a lot. For now, I define a dfs func to search transitive graph to find Message. And I will switch this package to protocompile next time, cause of the project ddl🤦
