### ISSUE TITLE
message.GetKnownFields() / message.FindFieldDescriptorByName() only returns fields which were not created dynamically

### ISSUE THREAD

**Issue by AndrewHogg** [jhump/protoreflect#62]
If you create a message with some fields dynamically added, the .GetKnownFields() method does not return them in the list - they are also not accessible by the .FindFieldDescriptorByName method.

If I store a map of the fieldDescriptors I created,  I can use that to access them and set values on the message, so there is a workaround that way.

**Comment by AndrewHogg** [comment]
Ignore - its a .Build() issue and assigning back.

**Comment by jhump** [comment]
Do you mind elaborating on "its a .Build() issue"? Is it an issue in the builders? I double-checked the implementation of `GetKnownFields` and `FindFieldDescriptorByName` in `dynamic.Message`, and it they should be able to find any field where a call to `SetField` or `TrySetField` was successful (even if the descriptor used to construct the message did not include these fields).

**Comment by AndrewHogg** [comment]
The issue comes from trying to use a proto file as an initial structure and then adding to it - I am unable to add fieldDescriptors and build them into the parent message - which is why they are not known. I'm trying to build up a reproduction scenario to demonstrate it - but extending an existing message dynamically with the fields being 'known' is difficult.

**Comment by AndrewHogg** [comment]
Figured it out, once I get a builder from message, and have added field, I have to use .GetParent() a few times to get to the message root and build that back to a descriptor.

**Comment by jhump** [comment]
@AndrewHogg, I would love to see a repro case, because (if I understand correctly) that should not be necessary.

When you create a builder from a message and then build it back into a descriptor, it implicitly converts its ancestor descriptors and also builds them back into ancestor descriptors, so the resulting modified descriptor should have the same "context" and thus be usable in dynamic messages constructed with the original descriptor.

Feel free to re-open this issue and change the description to be more precisely describe the problem.
