### ISSUE TITLE
Loading a protobuf import path and dynamic messages

### ISSUE THREAD

**Issue by guymolinari** [jhump/protoreflect#630]
I am looking to load up a non-trivial protobuf descriptor tree by pointing to a base directory path.   desc.LoadFileDescriptor() does not work.   I'm sure there is a way to get this setup properly but it is not clear from the case cases how to do this.

Ultimately I want to deserialize protobuf messages arriving on kinesis without a dependency on protocol

Is this supported?   If so, can you point me to an example?

**Comment by jhump** [comment]
@guymolinari, that would not be the function to use. Apologies if its docs are not clear. The Go docs state:
> LoadFileDescriptor creates a file descriptor using the bytes returned by proto.FileDescriptor. Descriptors are cached so that they do not need to be re-processed if the same file is fetched again later.

If we then look at the referenced (`proto.FileDescriptor`)[https://pkg.go.dev/github.com/golang/protobuf@v1.5.4/proto#FileDescriptor] function, we see that it returns descriptors for protocols that are _linked in_. In other words, if you generate Go code for the file, then you can use the same path provided to `protoc` (or the path relative module root if using `buf`) to do code generation as the argument, it will load the file descriptor that is embedded in the generated code.

(This is also discussed in the package docs for the `desc` package [here](https://pkg.go.dev/github.com/jhump/protoreflect/desc#hdr-Loading_Descriptors).)

To load a serialized file descriptor from the file system, you would need to first read the files and de-serialize into `*descriptorpb.FileDescriptorProto` instances (using `proto.Unmarshal`), and then you could use `desc.CreateFileDescriptor`.

Note however that the `desc` package is only in v1 and is deprecated. The upcoming v2 will not have any such package because the Go Protobuf runtime (in `google.golang.org/protobuf`) now provides support for dynamic descriptors and dynamic messages. To do this with that module, you'd use [`protodesc.NewFile`](https://pkg.go.dev/google.golang.org/protobuf/reflect/protodesc#NewFile).

For both of these approaches, you must load a file's imports before you can load the file itself. With the Go Protobuf runtime and the `protodesc` package, you could create a `*protoregistry.Files` to be your resolver and register each file with that registry as you build it.

**Comment by guymolinari** [comment]
Closing this issue.
