### ISSUE TITLE
dynamic.MarshalJSON - Crashes when marshaling message with repeated, packed field

### ISSUE THREAD

**Issue by pboyer** [jhump/protoreflect#8]
Howdy @jhump!

Message definition:

```
message point_list {
	repeated double point = 1;
}
```

Message instantiation:

```
msg := &pointline.PointList{
	Point: []float64{ 1,2,3 },
}
```

Stack trace (some parts omitted):
```
panic: runtime error: comparing uncomparable type []interface {} [recovered]
	panic: runtime error: comparing uncomparable type []interface {}

goroutine 8 [running]:
panic(0x531fa0, 0xc420284680)
	/bin/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420094540)
	/bin/src/testing/testing.go:579 +0x25d
panic(0x531fa0, 0xc420284680)
	/bin/src/runtime/panic.go:458 +0x243
/vendor/github.com/jhump/protoreflect/dynamic.(*Message).internalSetField(0xc42015fe60, 0xc42027bf10, 0x4f8260, 0xc420241e60)
	/vendor/github.com/jhump/protoreflect/dynamic/dynamic_message.go:362 +0x3df
/vendor/github.com/jhump/protoreflect/dynamic.(*Message).unmarshalKnownField(0xc42015fe60, 0xc42027bf10, 0xc42027bf02, 0xc42015fd80, 0xc420249f80, 0x3)
	/vendor/github.com/jhump/protoreflect/dynamic/binary.go:583 +0x9a2
/vendor/github.com/jhump/protoreflect/dynamic.(*Message).unmarshal(0xc42015fe60, 0xc42015fd80, 0x8a300, 0xc420094600, 0x0)
	/vendor/github.com/jhump/protoreflect/dynamic/binary.go:381 +0x171
/vendor/github.com/jhump/protoreflect/dynamic.(*Message).UnmarshalMerge(0xc42015fe60, 0xc4201cd9e0, 0x1a, 0x20, 0xc420266750, 0x3100)
	/vendor/github.com/jhump/protoreflect/dynamic/binary.go:354 +0x92
/vendor/github.com/jhump/protoreflect/dynamic.(*Message).Unmarshal(0xc42015fe60, 0xc4201cd9e0, 0x1a, 0x20, 0xc4202667f8, 0x3100)
	/vendor/github.com/jhump/protoreflect/dynamic/binary.go:347 +0x65
```

**Comment by pboyer** [comment]
I plan on starting in on this and #5 tomorrow because they're high value for me. If you can give me any breadcrumbs or if you have some higher frequency contact method (e.g. gitter), it might help. Best regards and thank you for this wonderful library!

**Comment by jhump** [comment]
This was a simple one. I have a test case that should have covered it, but the test uses a `syntax = "proto2"` file. This only happens with proto3. I merged a fix, but was too lazy to create a repro test case and verify. So please try it out and let me know whether it worked.

**Comment by jhump** [comment]
Regarding the other one (#5), you'll want to do something like so:

* Add a `MarshalJSONOpts` struct to store flags. For now, it may only be the one: `EmitDefaults` (that's what it's called in `jsonpb.Marshaler`.
* Add an overloaded marshal method that accepts options. (You could even update the existing `MarshalJSONIndent` to just delegate to this new overload and include `Indent` as an option.)
* Thread the options through the various marshal methods.
* In what is currently `marshalJSON(b *indentBuffer)`, you'll want to change the main loop of known fields to conditionally include all fields, not just those present.
  * "All fields" would be everything in `m.md.GetFields()` as well as anything in `m.extraFields` where `!fd.IsExtension()`.
  * You could accomplish this by adding a flag to `knownFieldTags()` so that it can collect the tags and sort them (deterministic output FTW!).
  * Inside the loop, getting the value from the map could suddenly return `nil`. If `nil`, you probably want to replace the value with `fd.GetDefaultValue()` (which can still be `nil` for messages -- see next bullet).
  * In `marshalKnownFieldJSON`, after it writes the field name, just emit `null` and return if `v == nil`.
* I *think* that the unmarshal side will already work with `null` values in the JSON. (Just read through some code, and it should be right. But I don't have a test to prove it ... yet!)

**Comment by pboyer** [comment]
@jhump Thanks for the tips! _Goes to work_.
