### ISSUE TITLE
An issue in parsing protobuf with MethodOptions

### ISSUE THREAD

**Issue by tfeng** [jhump/protoreflect#87]
I have a proto file that extends google's MethodOptions to annotate methods with additional validation logic.

During debugging, I found an issue in protoreflect that causes the MethodOptions of a latter method to overwrite the MethodOptions of the previous method. The problem could have wider impact than just this specific case.

An example proto file is like this:
```proto
service User {
    rpc UserAuth(Request) returns (Response) {
        option (validator) = {
            authenticated: true
            permission: {
                action: login
                entity: "client"
            }
        };
    }

    rpc Get(Request) returns (Response) {
        option (validator) = {
            authenticated: true
            permission: {
                action: read
                entity: "user"
            }
        };
    }
}
```

In the parse result, the option of the second (Get) method overwrites the option for the first (UserAuth) method.

I have a fix. I will submit a PR to resolve this issue.

**Comment by jhump** [comment]
@tfeng, I think you were using an older version of the library. As of #77, the computed aggregate string no longer has any actual bearing on how the aggregate gets transformed into an option in the descriptor.

So this bug should be fixed with the latest version of the repo, even without your pull request. Can you double-check to let me know?
